### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by RuneBergh** [CPChain/chain#1]
By following the guide this runtime error is experienced: 
INFO[01-11|16:36:30.818] Imported new chain segment                    blocks=14 cache="23.24 kB" elapsed=16.075ms hash=0x786ad8bcfef67f7e107099a723643f3e602d156500450858ff6b93d9e6ba09de mgas=0.168 mgasps=10.450687776558324 number=505439 txs=8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xba1f8d]

**Comment by Stef3478** [comment]
Some extra info about the system I got the runtime error reported above:

**Comment by millennium-falcon42** [comment]
thanks for reporting this.

@alex031029 will triage this.

**Comment by alex031029** [comment]
May I know what command you use when this runtime error occurs? @RuneBergh

**Comment by alex031029** [comment]
We updated the structure of transactions, which makes the current master version cannot be compatible with testnet. The reason we have yet update testnet is that the current master is not as stable as we expected. For the case you guys willing to use the testnet now, you may check the commit 3c384f6e10f626f66226783537fc4fc6931d7c3b. You can also choose to wait some days, then we can get the code and testnet compatible with each other.

**Comment by Stef3478** [comment]
Thanks for the update Alex!
