### ISSUE TITLE
Problem to get run the Node

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#10]
**Where does the bug occur?**
When I start './cpchain run --datadir ./datadir     --unlock xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     --rpcaddr 127.0.0.1:8501 --port 30311 --mine     --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber
'

**Describe the bug**
Look on screenshot

**To Reproduce**
Steps to reproduce the behavior, and the commands you use.

**Expected behavior**
No Errors

**Screenshots**
![Bildschirmfoto von 2019-05-08 10-27-57](https://user-images.githubusercontent.com/24302453/57361648-2c530600-717d-11e9-93b8-283314627388.png)

** Configuration (please complete the following information):**
 -  Ubuntu 18.04
 -  0.2.3

**Additional context**
What means: "not enough signatures in block" and why "verifying validator signatures failed"?

**Comment by Mateus224** [comment]
I started this program on my Laptop too yesterday and there I get the same errors. And today I started this on a third old AMD computer. Here I DONT get this Errors and it looks good for now...

**Comment by Mateus224** [comment]
It works on my computer (i-5 Processor) if i use the cpchain-linux-amd64-v0.2.4 version. Not sure why AMD but it works

**Comment by alex031029** [comment]
Thanks for your update. This issue won't be closed until we figure out the reason.
