### ISSUE TITLE
Campaign Stop Issue

### ISSUE THREAD

**Issue by seerhaad-dev** [CPChain/chain#100]
Hi there, 

Whenever I want stop my RNode with the following command, I get the error below. Can you help me about it ? 

./cpchain campaign stop --keystore ./datadir/keystore/UTC--

INFO[01-04|13:30:35.679] Stop Mining...
INFO[01-04|13:30:35.680] error:The method miner_stop does not exist/is not available

** Configuration (please complete the following information):**
 - OS: Linux (centos 7.7.1908)
 - cpchain version [e.g. 0.5.2]

**Comment by CPC-Yao** [comment]
Did you enable rpcapi when you started cpchain?
Cloud you please tell me the command you use to start cpchain?
