### ISSUE TITLE
cant get back my 200kcpc from rnode,spark program.

### ISSUE THREAD

**Issue by mexcpc** [CPChain/chain#101]
Hello i need help.
I used to have a Rnode back in few months ago. I participated in spark program. I used Rnode on VULTR. Then i stopped paying it and i destroyed the server.
Now i would like to get back my 200kcpchain. I used few commands but it didnt work or said "your node is already offline" or something like this.
Is there any easy way to get my 200k cpc back? Any admin could send them back to me or explain me how to get back them on windowns on my laptop. 
Thanks in advance.
Mex

**Comment by mexcpc** [comment]
I'm still waiting for answer/help. Hopefully after 9th February i will get an answer.

**Comment by CPC-Yao** [comment]
Sorry for the very late reply.
You have to sync blocks again before running "campaign stop" command.

**Comment by mexcpc** [comment]
I have been trying to get alive my rnode again and then stop but i couldnt. I was trying to do that on my laptop but i cant get it working. I used to rnode on vultr but then i stopped paying for it and now i dont know how to get it working back on my laptop. Is there any possibility for You to manually send them back to my wallet? Or help me to get it back by connecting with me via Teamviewer?

**Comment by CPC-Yao** [comment]
It's not a good idea that I connect to your laptop for security reasons.  I suggest you restart the machine on vultr and run rnode program according to our documentation. Syncing blocks only takes a few hours, and paying by time is not too expensive.

**Comment by mexcpc** [comment]
INFO[02-24|22:15:56.291] Stop Mining...
INFO[02-24|22:15:56.296] Stop Mining Success
INFO[02-24|22:15:56.296] Quit Rnode...
INFO[02-24|22:15:56.305] error:nonce too low

does it mean i have stopped my node?

**Comment by CPC-Yao** [comment]
You could use `./cpchain campaign status` to check.

**Comment by mexcpc** [comment]
![status](https://user-images.githubusercontent.com/50459382/75481643-ad48eb80-59a3-11ea-816a-4bfef5eba407.png)

**Comment by mexcpc** [comment]
After typing the command it asks me for password so i type the password and this is the result i get above.

**Comment by CPC-Yao** [comment]
Please make sure you have synced all blocks before executing any commands. 
And you could check if you are still rnode through rnodes list.
https://cpchain.io/explorer/rnode/
