### ISSUE TITLE
Cannot sync time even after following the guide

### ISSUE THREAD

**Issue by Somstradamus** [CPChain/chain#104]
**Where does the bug occur?**
The RNode shell

**Describe the bug**
When I start the RNode, it says 

WARN[03-21|14:57:57.260]

################################################################################
################################################################################

        System clock need to be synchronized.
        Refer to the LINK BELOW for detailed explanation.

        https://docs.cpchain.io/misc/faq.html#ntp

################################################################################
################################################################################

goroutine 1 [running]:
main.run(0xc0000db600, 0x18, 0xc0002ebab0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/cmd/cpchain/cmd_run.go:117 +0x1c4
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.HandleAction(0xf321a0, 0x123a420, 0xc0000db600, 0xc0000db600, 0xc0002ebd78)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/app.go:501 +0xcf
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.Command.Run(0x1098685, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10b58d6, 0x12, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/command.go:165 +0x427
bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli.(*App).Run(0xc000129a40, 0xc000092000, 0x5, 0x8, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/urfave/cli/app.go:259 +0x6d6
main.main()
        /ext-go/1/src/bitbucket.org/cpchain/chain/cmd/cpchain/main.go:66 +0x56

FATA[03-21|14:57:57.263] system clock need to be synchronized.there is more than 10 seconds gap between ntp and this server

**To Reproduce**
cpchain-windows-4.0-amd64.exe run --unlock 0xE4F8bEc7cD890aCe1C0c52C65Bc3B6DF97a81fE2 --mine

**Expected behavior**
The RNode to start as usual.

** Configuration (please complete the following information):**
 - OS: Windows 10 64
 - cpchain version 0.5.2

**Additional context**
It happened before, but then I just restarted the WiFi and it solved it every time. But now this fix doesn't work anymore.

**Comment by CPC-Yao** [comment]
Please synchronize your clock using Windows 10's settings. You could google "windows clock sync".

**Comment by hvredevoort** [comment]
Open a PowerShell window in Administrative mode

Run following commands
w32tm /config /manualpeerlist:pool.ntp.org /syncfromflags:MANUAL
Stop-Service w32time
Start-Service w32time
w32tm /resync

![image](https://user-images.githubusercontent.com/6986026/78221761-2b8e3580-74ee-11ea-8a84-95fcdf46a10f.png)
