### ISSUE TITLE
Missing CPC on Mainnet

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#105]
Hi There,

It seems that not all CPC on mainnet is visible currently, so therefore we cannot conclude what the total supply is on mainnet. According to the whitepaper it should be 1B, but we are unable to verify if this is true.

Here is my analysis:

When you add all balances of all known wallets on mainnet there is currently ~93M CPC missing.
This means there is a certain amount of CPChain that is located in unknown (or hidden) wallets.
Because we know now that there are unknown wallets holding CPC it is also not proven wat the total supply is.

(A known wallet is a wallet that either send CPC or received CPC during a transaction on mainnet.)

The amount of CPC generated is generated through the contract code, when i try to reverse engineer that code i still cannot find out where that 93M CPC is, or how much is created when launching mainnet nor can any regular person without knowlegde of this matter.

I therefore ask the team to clarify with evidence what the total supply is on mainnet.

Have a look here to see which wallets are identified and their balances:

https://cpcstats.com/wallets/

**Comment by CPC-Yao** [comment]
The total CPC issuance is 1 billion. The missing part is the block reward for the next 5 years.
