### ISSUE TITLE
How to compress the db or start the RNode from other drive than C: on Win10 64?

### ISSUE THREAD

**Issue by Somstradamus** [CPChain/chain#106]
I heard that the command to compress the db is bugged so unusable for now. So I would like to know how can I run the node from a spare HD on Win10 64? Is it possible?

**Comment by CPC-Yao** [comment]
You can specify another directory to store data by adding the flag "--datadir path/you/want" in the command.

**Comment by hvredevoort** [comment]
it also needs some cleanup if you've used ~/.cpchain  if you haven't used the default directory
and any other directory you have mistakenly tried
