### ISSUE TITLE
How come one of my nodes is underperforming compared to my others with same specs?

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#107]
Hi,

I have three nodes running, one of them is constantly perfoming less than the other 2 with same specs, in the same cloud, with more or less the same amount of balance.

I would think they would seal amount more or less the same amount of blocks, but the node is sealing almost less than half of the blocks compared to the other 2.

This is going on now for more than a month. 

What can i do to improve this node?

**Comment by CPC-Yao** [comment]
There is a certain randomness in the sealing blocks.  All nodes are divided into two parts according to the ranking, and the high rpt value part has a higher probability of generating blocks. Maybe your three nodes are just on the dividing line（1 low and 2 high）.
