### ISSUE TITLE
Big difference in Reputation

### ISSUE THREAD

**Issue by sysadmin42** [CPChain/chain#11]
Team,

When looking at https://cpchain.io/explorer/rnode/, we see 14 nodes with reputation of 28000, and 13 with 8000.
Isn't this a rather strange distribution?
My rnode has only 8000, didn't produce many blocks, while the account is quite big, and the VPS is sufficient?

Regards,
Bernard

**Comment by alex031029** [comment]
After modifying the RPT calculation method in version 0.2.8, the problem is fixed!
