### ISSUE TITLE
Error in Claiming campain when starting node with v0.2.4

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#12]
I have updated to v0.2.4

When i run the node, i get this error:

 Error in claiming campaign                    Line="admission/admission.go:353" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

Not sure how to antipicate on this.

**Comment by siebeneicher** [comment]
I encouter the same issue, always when starting the node.

**Comment by siebeneicher** [comment]
Got the error again. Here is my log:

`INFO[05-08|17:52:45.048] Imported new chain segment                    Line="core/blockchain.go:1551" blocks=1 cache="0.00 B" elapsed=4.026ms hash=0x5785b2e65743249cd2a2ff03c927ba00b04d9ce1e0b8f6dbd06e4a4f05f5377f mgas=0 mgasps=0 number=350641 txCounterAfterStartup=54 txs=0
INFO[05-08|17:52:46.068] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=9740
INFO[05-08|17:52:46.068] Start campaign for dpor proposers committee   Line="admission/admission.go:93"
INFO[05-08|17:52:46.132] found nonce                                   Line="admission/work.go:137" block hash=0x2af3fe250bf65ea0ddf3eb036c578642cb1bb3d33b3530aed2bb8d1ce50003af difficulty=12 nonce=4460 sender=0x6026AB99F0345E57c7855a790376b47eb308cB40 timeCost(s)=0.060086929
INFO[05-08|17:52:46.882] found nonce                                   Line="admission/work.go:137" block hash=0x2af3fe250bf65ea0ddf3eb036c578642cb1bb3d33b3530aed2bb8d1ce50003af difficulty=6 nonce=61 sender=0x6026AB99F0345E57c7855a790376b47eb308cB40 timeCost(s)=0.810154453
WARN[05-08|17:52:47.335] Error in claiming campaign                    Line="admission/admission.go:353" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
INFO[05-08|17:53:05.046] Imported new chain segment                    Line="core/blockchain.go:1551" blocks=1 cache="0.00 B" elapsed=3.626ms hash=0xa0addb6290f729a406f7568babc2332dfaf317aec04bbf0f9e59b082da373dc9 mgas=0 mgasps=0 number=350642 txCounterAfterStartup=54 txs=0
INFO[05-08|17:53:25.048] Imported new chain segment `

**Comment by hvredevoort** [comment]
I'm seeing the same
![image](https://user-images.githubusercontent.com/6986026/57392237-888b4980-71c0-11e9-875d-c70a0d7b6f99.png)

**Comment by siebeneicher** [comment]
It prevents from sealing blocks over and over again.

+1 high priority

**Comment by alex031029** [comment]
We've acknowledge this problem. We know it is AC (admission control), which is invoked for campaign claimer, causing this problem. I believe it won't take too long to solve it.

**Comment by hvredevoort** [comment]
I'm now seeing "sealing blocks" 
![image](https://user-images.githubusercontent.com/6986026/57425099-43940100-721a-11e9-855e-816d5cb41455.png)

**Comment by hadox** [comment]
FYI:
I just noticed the same issue (I'm still one 2.3 though)
https://github.com/CPChain/chain/issues/12
![image](https://user-images.githubusercontent.com/33176668/57431627-b362b580-7233-11e9-9b3d-952ebb528998.png)

**Comment by hadox** [comment]
FYI: 
I just notice the same issue (still running on 2.3 though)
![image](https://user-images.githubusercontent.com/33176668/57431700-e73ddb00-7233-11e9-8491-4db12b70c391.png)

**Comment by SanShiner** [comment]
error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction" comes also when I find a block and should be rewarded. Rewards stopped with 0.2.4 for me.

**Comment by hvredevoort** [comment]
I'm seeing this problem again

**Comment by dbchowdary** [comment]
I am getting this error able to produce 239 blocks now it stopped producing anything further getting this error and warning

**Comment by kbaf** [comment]
I just updated to v0.2.5 but the error remains to exist

it is not RNode, cannot participate campaign  Line="dpor/consensus.go:208"

Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

**Comment by X-fighter11** [comment]
I am getting this same error and I havent any blocks anymore. Running v.0.2.6

Error in claiming campaign Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

**Comment by equilibrium20** [comment]
No More blocks or Transactions in v 0.2.6
Error in claiming campaign                    error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
The above error every time.
![gasError](https://user-images.githubusercontent.com/50518870/57569421-c48dfc80-73c2-11e9-86ff-e0b57f07ef70.gif)
