### ISSUE TITLE
My node is an rnode but cannot see this in console app

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#13]
I get opposing information
In explorer I see my node is elevated to rnode

When running console app I don't see this.

**Where does the bug occur?**
[e.g. the chain, the wallet, the console or the explorer]
console and explorer

**What is your wallet address and your balance?**
https://cpchain.io/explorer/address/1d93a6d7c9169b06f4c5fb8f9307c69192865ce3

**Describe the bug**
I see two different status in explorer and console

**Screenshots**
![image](https://user-images.githubusercontent.com/6986026/57380335-19562b00-71a9-11e9-8f8e-fb74f77a92df.png)
![image](https://user-images.githubusercontent.com/6986026/57380402-3b4fad80-71a9-11e9-91cb-674821a962c5.png)
![image](https://user-images.githubusercontent.com/6986026/57380429-4571ac00-71a9-11e9-93fd-6f33284ee04a.png)
![image](https://user-images.githubusercontent.com/6986026/57380448-4efb1400-71a9-11e9-923d-24b8c59799fd.png)

Question:
How do I know for sure the rnode is actually running?
Why does console not show this?

** Configuration (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - cpchain version [e.g. 0.2.3]

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by Liaojinlo** [comment]
The way of get RNode status had be changed, so console need upgrade. We'll keep this issue open until we release a new version.

**Comment by hvredevoort** [comment]
Thank you
