### ISSUE TITLE
www.cpchain.io + explorer is down

### ISSUE THREAD

**Issue by hadox** [CPChain/chain#14]
**Where does the bug occur?**
Website (http://www.cpchain.io) & explorer (https://www.cpchain.io/explorer) are most of the time completely down or really slow
![image](https://user-images.githubusercontent.com/33176668/57393563-a4dcb580-71c3-11e9-8550-c7cd35d02bbc.png)

**Comment by siebeneicher** [comment]
When the team is sleeping and its down for over the whole night, well... its not a thing for overseas.

**Comment by Liaojinlo** [comment]
sorry, we'll slove this bug and add health check for cpchain.io today.
