### ISSUE TITLE
Explorer - List of RNodes also shows Proposers

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#15]
In CPChain Explorer:
List of Rnodes should only show Rnodes
List of Proposers should only show Proposers

![image](https://user-images.githubusercontent.com/6986026/57425545-d5e8d480-721b-11e9-9633-9d729c4d36da.png)

**Comment by alex031029** [comment]
We will consider your advice. 
But at the current stage, we put the highest priority in maintaining the chain.
