### ISSUE TITLE
Transaction stuck sometimes

### ISSUE THREAD

**Issue by dbchowdary** [CPChain/chain#16]
Hi there, 
This is CPChain team. Note that this is for bug report. If you are requesting a feature, please select *Feature Request* template. 

**Where does the bug occur?**
while mining sometimes transaction getting stuck not sure if it is an issue with cmd /windows version/network

**What is your wallet address and your balance?**
https://cpchain.io/explorer/address/ed952d8617a1502078493f2f7a28e8a182e7b381

**Describe the bug**
Now rebroadcasting waiting txs

**To Reproduce**
Steps to reproduce the behavior, and the commands you use.
Not sure because it occurs only sometimes when the transaction stucks

**Expected behavior**

it should work as usual as regular mining not getting stuck  

**Screenshots**
<img width="719" alt="Capture" src="https://user-images.githubusercontent.com/16735541/57428353-91464480-71ed-11e9-9b68-8b45eaf620a0.PNG">

** Configuration (please complete the following information):**
 - OS: windows 2016
 - cpchain version  0.2.4

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
You can omit it, these logs do not affect your mining process. 

This warning is only for dev debug purpose. We will shift it to debug level in future release.
