### ISSUE TITLE
CPC default proposers twice in proposer list 

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#17]
Wrong filling of the proposers list

**Where does the bug occur?**
This occurs in the proposer list of the explorer

**What is your wallet address and your balance?**
Not relevant

**Describe the bug**
The proposers list should be filled with Rnodes.
Due to some malfunctioning (probably caused by the AC part (campaigne claiming)) their are not enough Rnode proposers available.
To keep the system up and running default proposers from CPC will be inserted by the system.

If this occurs a default proposer can be in the list more than once which is not acceptable.
(This is discussed with Yanchen Shi, he can give more detail if necessary)

**To Reproduce**
Watch the proposers list at this moment, On regular base 2 composers (CPC default composers!) with the same address are in the list

**Expected behavior**
Only real RNodes/Composers should be in the list. No CPC default composers!

**Screenshots**
![proposers list](https://user-images.githubusercontent.com/24922860/57451536-dc9a3a80-7261-11e9-8974-f5f1289315df.jpeg)

** Configuration (please complete the following information):**
Not relevant since it is backend (CPC side)
 - OS: Centos 7
 - cpchain version 0.2.4

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
I have acknowledged this issue from OP in telegram. 

These proposers are default proposers, which are our servers. They are designed for retaining the throughput of the chain. It is impossible for normal proposer sealing more than one blocks in a single term. Default proposers served as backups, fill the proposers committee if there are not enough applicable candidates. 

This problem can be regarded an another manifestation of AC bug. And we are going to solve it.
