### ISSUE TITLE
Blocks are created without reward or producer address

### ISSUE THREAD

**Issue by L0ut** [CPChain/chain#18]
Hi there, 
This is CPChain team. Note that this is for bug report. If you are requesting a feature, please select *Feature Request* template. 

**Where does the bug occur?**
The chain, it's visible in the console

**What is your wallet address and your balance?**
0x295226D148533706caEe6f94917B4134f53C1180
166.981 cpc

**Describe the bug**
A block is sealed by my address but when looking on the explorer there is no address or reward visible. Also no rewards are added in the console.

**To Reproduce**
-

**Expected behavior**
a block sealed should be link the address to the block and pay out a rewards. Non of this happened according to the explorer and also on the console it's not visible when looking up  the account

**Screenshots**

** Configuration (please complete the following information):**
 - OS: Windows 2016
 - cpchain version 0.2.4

**Additional context**
It was the first time this occured by my knowledge
![sealed blocks 300 301 302](https://user-images.githubusercontent.com/50440757/57464277-b5049b80-727c-11e9-9e02-970360253d85.jpg)
![explorer 300 301 302](https://user-images.githubusercontent.com/50440757/57464282-b7ff8c00-727c-11e9-8963-fb23de22ff13.jpg)
![block 358300](https://user-images.githubusercontent.com/50440757/57464288-b930b900-727c-11e9-84ff-7963b49763cb.jpg)

**Comment by alex031029** [comment]
I have checked our explorer. Despite that your blocks (358300,358301,358302) have been successfully sealed, these three blocks have not passed validation. 

There are several reasons leading to a failure in validation:
1. Low CPU capacity 
2. Low network bandwidth
3. Proposer deliberate misbehavior

I met another guy in China reporting a same issue as yours. We are now investigating validator's logs. And if possible, can you post your specs about CPU and bandwidth here?

**Comment by alex031029** [comment]
One more thing, the Chinese met the same issue reported that he had never met this issue when he was using 0.2.3 version. After updating to 0.2.4, this problem occurs constantly. 

Do you encounter the same situation as him?

**Comment by L0ut** [comment]
i'm not 100% sure if it happend more than once. It's definitly not low bandwith or CPU. I also didn't do anything specific at that moment so it's not possible to replicate.

My spec are:
- 320GB storage
- 6 CPU
- 16GB Memory
- 5TB bandwith
- Windows 2016

**Comment by alex031029** [comment]
Your specs are terrific. It confuses me since we didn't modify a single bit about consensus and p2p connection in 0.2.4. 
Another question. Do these impeach blocks occur occasionally or constantly after you updated 0.2.4?

Thanks for your useful info. Hope we can figure it out soon.

**Comment by L0ut** [comment]
They just happened once as far as I know, i probably caught it by luck since i'm not glued to my console screen all day

**Comment by alex031029** [comment]
Understood. In case you meet this problem again, please post here.

**Comment by alex031029** [comment]
Here I merged this issue to #27 and close it.
