### ISSUE TITLE
failed to unlock account, help.

### ISSUE THREAD

**Issue by mexcpc** [CPChain/chain#19]
Hello,
I have problem with running my test node.
Im getting this message: "failed to unlock account <no key for given addres or file>

This is the steps i do:
1. cd Desktop
2. cpchain run --datadir ./datadir --unlock "here i put my public key" --rpcaddr 127.0.0.1:8501 --port 30311 --mine  --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber
3. i put my password
4. and now i get this failure message.

This is my MEW wallet: 0xa62f6479AF603ecEF9f432A4C1619B4717143e1f
Please help me to set it up or tell my why i can't.
If u need more info from me, ask.

**Comment by L0ut** [comment]
It seems like you're entering the wrong password.

**Comment by alex031029** [comment]
It is more likely that some of your operations are not proper, like wrong password. If you can repeat this problem, and confirm that your wallet address, keystore file path and password are correct, please comment here.

**Comment by mexcpc** [comment]
i forgot to upload a picture here it is:
https://imgur.com/a/cC4X9k0
my keystore folder is empty, its supposed to be something there?

**Comment by alex031029** [comment]
Have you create an account? 
You are required to create an account by following command.
`./cpchain account new account --datadir ./datadir`
It will create an account file in ./datadir.

**Comment by mexcpc** [comment]
I have created an account for sure, i have some folders and files in datadir folder. I will make screenshot of it when im home. (if i got the public key or how its called i guess it means i have made the account). Correct me if im wrong.

**Comment by mexcpc** [comment]
https://imgur.com/qTFlq11
https://imgur.com/12C1aTv
https://imgur.com/5ziUSwR
https://imgur.com/V1bTtIE
https://imgur.com/BICX2l4

**Comment by wuxiangzhou2010** [comment]
@mexcpc  your keystore folder is empty, it should contain a keystore file whose name is  prefixed with `UTC-` as in below image.
 BTW,   basically  you can  treat a keystore file  as an account  which contain public key and can derive your private key with a password. The private key is used to sign transactions...

![WeChatefc26e48910f77fd8bb83766c3145183](https://user-images.githubusercontent.com/3865271/57565041-a935e800-73e8-11e9-81b5-408547fcf429.png)

**Comment by mexcpc** [comment]
Could u explain me in easy words what im supposed to do to make it working please?

**Comment by alex031029** [comment]
`cd Desktop
cpchain run --datadir "**here you should put your keystore file path**" --unlock "here i put my public key" --rpcaddr 127.0.0.1:8501 --port 30311 --mine --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber
i put my password`

**Comment by mexcpc** [comment]
can we speak on telegram trough microphone so we cancommunicate better?

**Comment by alex031029** [comment]
Sure! Just message me.

**Comment by mexcpc** [comment]
how can i find you?

**Comment by mexcpc** [comment]
Ive been calling you but u seemed to be busy because u didnt answer. I have to leave my home atm, i hope we can contact later..

**Comment by mexcpc** [comment]
> Sure! Just message me.
Hey Alex we can contact now.
