### ISSUE TITLE
[2.5] not enough money to become RNode 

### ISSUE THREAD

**Issue by hadox** [CPChain/chain#20]
**Where does the bug occur?**
v 2.5

**What is your wallet address and your balance?**
+200k

**Describe the bug**
Starting 2.5 returns "not enough money to become RNode "
Don't have this problem with 2.3/2.4

**Screenshots**
![image](https://user-images.githubusercontent.com/33176668/57567040-abda1280-73d3-11e9-9769-49e4047d550a.png)

** Configuration (please complete the following information):**
 - Ubuntu 19.04
 - cpchain 2.5

**Comment by alex031029** [comment]
One possible reason is that we update claim campaign smart contract, as we described in this issue:
https://github.com/CPChain/chain/issues/21
We will follow up on this issue to investigate the situation.

**Comment by tass21fr** [comment]
This issue has not been solved by 2.6 version

**Comment by dbchowdary** [comment]
yes i am getting this error

**Comment by alex031029** [comment]
It problem is confirmed as another manifestation of #21 . Those own 400k can deposit twice, as described in #21 , and the rest cannot afford the second deposit as shown in this issue. 

We have written a script getting everyone refunded, as long as he/she runs a version later or equal than 0.2.6. For those who have get refunded yet, please private message me in telegram.
