### ISSUE TITLE
My address sent another 200k CPChain after upgrading to 0.2.5

### ISSUE THREAD

**Issue by atmo4th** [CPChain/chain#21]
After upgrading my node to 0.2.5 i noticed that my address sent additional 200000 CPC (It sent 200k CPC previously during the start of beta test). I assume that this is the fee for becoming Rnode/Proposer Node, but is it supposed to substract the 200k CPC twice?

** Configuration (please complete the following information):**
OS: Ubuntu 19.04
CPChain 0.2.5

Please let me know if you need more info.

**Comment by alex031029** [comment]
@HKet informed about this problem in telegram.
Despite it looks weird, the extra deduction is as our expectation. In 0.2.5, we updated claim campaign smart contract. The new contract deducts each miner another 200k as deposit. For the 200k in the old deposit, we is going to write a loop to refund all participants.

**Comment by alex031029** [comment]
We have implemented a script which refunds deposit in old smart contract iteratively. This script is executed manually time to time till all addresses get refunded.
Note that participants using version lower than 0.2.6 cannot get refunded, and unable to claim campaign now.

**Comment by HKet** [comment]
Hi,

Although the refund-actie did work and I am on 2.6 i did not get any block refund-action anymore. And yes i am on the RNode list. 

A lot (and i think ALL people) are complaining about this. 

And as explorer is showing a lot of blocks are processed. 

Grt,
Hans Ketelaars

**Comment by alex031029** [comment]
It problem is related of #20  . Those who own 400k can deposit twice, as described in this issue , and the rest cannot afford the second deposit as shown in #20 .

We have written a script getting everyone refunded, as long as he/she runs a version later or equal than 0.2.6. For those who have yet get refunded, please private message me in telegram.
