### ISSUE TITLE
Error: "verifying validator signatures failed" 

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#23]
**Where does the bug occur?**
the chain

**What is your wallet address and your balance?**
1d93a6d7c9169b06f4c5fb8f9307c69192865ce3 

**Describe the bug**
I regularly see 

**To Reproduce**
during sync of new chain segments I see a lot of "verifying validator signatures failed" 

**Expected behavior**

**Screenshots**
![verifying validator signatures failed](https://user-images.githubusercontent.com/6986026/57572305-a652eb80-7418-11e9-88d8-24fd41cd8226.png)

** Configuration (please complete the following information):**
 - OS: Windows Server 2016
 - cpchain version: 0.2.6
 - h/w 8GB, 6 cores

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
This WARNING is for debug purpose. We will adjust log hierarchy in later versions.
