### ISSUE TITLE
Error in claiming campaign 0.2.7

### ISSUE THREAD

**Issue by L0ut** [CPChain/chain#24]
Bug is still alive in the update
![error claiming campaign](https://user-images.githubusercontent.com/50440757/57625507-43865f00-7594-11e9-9868-82af2881c6b7.jpg)

**Comment by hvredevoort** [comment]
After moving my configuration to another server, I also got the Error in claiming campaign again

**Comment by alex031029** [comment]
We've acknowledged the problem. I will keep you updated.

**Comment by NielDS** [comment]
Intermittently seeing this error on 0.2.7. Not every time a new campaign starts ....30/40%

**Comment by alex031029** [comment]
This problem is another manifestation of #12 , caused by same code. We close it and merge this issue to #12 .
