### ISSUE TITLE
Proposer without sealing blocks

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#26]
**Where does the bug occur?**
chain

**What is your wallet address and your balance?**
If it is too private to answer, you can omit it. 

**Describe the bug**
I restarted with 0.2.7 and quickly became a proposer.
No blocks were sealed however

**To Reproduce**
Steps to reproduce the behavior, and the commands you use.

**Expected behavior**

**Screenshots**
INFO[05-13|15:59:16.153] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=10869
INFO[05-13|15:59:16.153] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-13|15:59:16.179] found nonce                                   Line="admission/work.go:137" block hash=0xce3616575dde39d17215bfcdd3cb7a7a0703689913b7c8e283f43aaa0cb96a4c difficulty=12 nonce=8 sender=0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3 timeCost(s)=0
INFO[05-13|15:59:16.632] found nonce                                   Line="admission/work.go:137" block hash=0xce3616575dde39d17215bfcdd3cb7a7a0703689913b7c8e283f43aaa0cb96a4c difficulty=6 nonce=24 sender=0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3 timeCost(s)=0.4531236
INFO[05-13|15:59:17.205] Submitted transaction                         Line="cpcapi/api.go:1448" fullhash=0x2d5d61c103081c3467bba8caa271afe533574936977e898bb71027b05e52dbed recipient=0xb8A07aE42E2902C41336A301C22b6e849eDd4F8B
INFO[05-13|15:59:17.205] Claimed for campaign                          CpuBlockNumber=391284 CpuPowResult=8 Line="admission/admission.go:323" MemBlockNumber=391284 MemPowResult=24 NumberOfCampaignTerms=3
INFO[05-13|15:59:25.076] Synchronization Started                       Line="syncer/syncer.go:430" local height=391285 peer=986b011a6cd9be25 peer.Head=0x9b5ff00a00e342fa3408fa81625897508b23af940810a439423be50ec01d8b17 peer.height=391286
INFO[05-13|15:59:25.084] Synchronization Started                       Line="syncer/syncer.go:430" local height=391285 peer=4888b71f5e2199be peer.Head=0x9b5ff00a00e342fa3408fa81625897508b23af940810a439423be50ec01d8b17 peer.height=391286
INFO[05-13|15:59:25.085] Synchronization Started                       Line="syncer/syncer.go:430" local height=391285 peer=0ab15a0aad44d8d7 peer.Head=0x9b5ff00a00e342fa3408fa81625897508b23af940810a439423be50ec01d8b17 peer.height=391286
INFO[05-13|15:59:25.086] Synchronization Started                       Line="syncer/syncer.go:430" local height=391285 peer=ae89a3eb8e3abd89 peer.Head=0x9b5ff00a00e342fa3408fa81625897508b23af940810a439423be50ec01d8b17 peer.height=391286
INFO[05-13|15:59:25.098] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="1.62 kB" elapsed=13.669ms hash=0x9b5ff00a00e342fa3408fa81625897508b23af940810a439423be50ec01d8b17 mgas=0 mgasps=0 number=391286 txCounterAfterStartup=35 txs=0
INFO[05-13|15:59:35.461] Synchronization Started                       Line="syncer/syncer.go:430" local height=391286 peer=986b011a6cd9be25 peer.Head=0x480bd0794ae7d1e0c8526328e2e338c73626cd01b473b8172f320161650c06ea peer.height=391287
INFO[05-13|15:59:35.461] Synchronization Started                       Line="syncer/syncer.go:430" local height=391286 peer=4888b71f5e2199be peer.Head=0x480bd0794ae7d1e0c8526328e2e338c73626cd01b473b8172f320161650c06ea peer.height=391287
INFO[05-13|15:59:35.473] Synchronization Started                       Line="syncer/syncer.go:430" local height=391286 peer=ae89a3eb8e3abd89 peer.Head=0x480bd0794ae7d1e0c8526328e2e338c73626cd01b473b8172f320161650c06ea peer.height=391287
INFO[05-13|15:59:35.519] Synchronization Started                       Line="syncer/syncer.go:430" local height=391286 peer=c934dea6caf76cc3 peer.Head=0x480bd0794ae7d1e0c8526328e2e338c73626cd01b473b8172f320161650c06ea peer.height=391287
INFO[05-13|15:59:35.539] Synchronization Started                       Line="syncer/syncer.go:430" local height=391286 peer=47d12c0863241f68 peer.Head=0x480bd0794ae7d1e0c8526328e2e338c73626cd01b473b8172f320161650c06ea peer.height=391287
INFO[05-13|15:59:35.644] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="88.80 kB" elapsed=176.758ms hash=0x480bd0794ae7d1e0c8526328e2e338c73626cd01b473b8172f320161650c06ea mgas=2.068161 mgasps=11.700476412193572 number=391287 txCounterAfterStartup=43 txs=8
INFO[05-13|15:59:45.068] Synchronization Started                       Line="syncer/syncer.go:430" local height=391287 peer=986b011a6cd9be25 peer.Head=0x42dfd819ee3d8f3b912be346881329ea3cea1cf8a226a8c49d3e63f895fe5097 peer.height=391288
INFO[05-13|15:59:45.075] Synchronization Started                       Line="syncer/syncer.go:430" local height=391287 peer=1fe6a765858ff1c0 peer.Head=0x42dfd819ee3d8f3b912be346881329ea3cea1cf8a226a8c49d3e63f895fe5097 peer.height=391288
INFO[05-13|15:59:45.075] Synchronization Started                       Line="syncer/syncer.go:430" local height=391287 peer=0ab15a0aad44d8d7 peer.Head=0x42dfd819ee3d8f3b912be346881329ea3cea1cf8a226a8c49d3e63f895fe5097 peer.height=391288

** Configuration (please complete the following information):**
 - OS: Windows Server 2016
 - cpchain version 0.2.7

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
It looks like a severe problem . And yet have I received similar error message from other participants. 
But I can hardly tell any these messages since they consists of no error, warning or fatal messages.

**Comment by alex031029** [comment]
@L0ut reported the same problem to me in telegram

**Comment by hvredevoort** [comment]
I'm sealing blocks since yesterday. My Proposer history now is 191 blocks (I think these are the sealed blocks, correct?)
https://cpchain.io/explorer/address/0x1d93a6d7c9169b06f4c5fb8f9307c69192865ce3

**Comment by alex031029** [comment]
@L0ut encountered this issue on 0.2.8 again. Here is the his error message.

INFO[05-14|21:18:41.790] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=11155
INFO[05-14|21:18:41.790] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-14|21:18:41.879] found nonce                                   Line="admission/work.go:137" block hash=0x7c44746873ccbafea3d24823571ff952f640816c2d21c5773e51f61880988f4f difficulty=12 nonce=3729 sender=0x295226D148533706caEe6f94917B4134f53C1180 timeCost(s)=0.0615247
INFO[05-14|21:18:43.378] found nonce                                   Line="admission/work.go:137" block hash=0x7c44746873ccbafea3d24823571ff952f640816c2d21c5773e51f61880988f4f difficulty=6 nonce=94 sender=0x295226D148533706caEe6f94917B4134f53C1180 timeCost(s)=1.5605358

**Comment by alex031029** [comment]
Since you have sealed blocks again, I am about to close this issue.
One possible reason for your case is that your RPT calculation was out-dated (old version cpchain). An old version cpchain calculates RPT and consider it's elected, while actually its calculation is wrong thus it is not elected.

**Comment by hvredevoort** [comment]
Thanks, good explanation
