### ISSUE TITLE
Error in claiming campaign 0.2.8

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#28]
**Where does the bug occur?**
the chain

**What is your wallet address and your balance?**
0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3

**Describe the bug**
After starting cpchain 0.2.8 multiple times already:
Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

**To Reproduce**
Start command

**Expected behavior**

**Screenshots**

D:\rn\cp>cpchain run --password .\password.txt --datadir .\datadir --unlock 1d93a6d7c9169b06f4c5fb8f9307c69192865ce3 --rpcaddr 127.0.0.1:8501 --port 30311 --mine --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber
INFO[05-14|13:17:13.705] init validators                               Line="configs/general.go:237" nodes="[enode://2ddfb534019e6b446fb4465742f266d04fae661089e3dac6a4c841ad0fcf5569f8d049203079bb64e20d1a32fc84b584920839a2120cd5e8886744719452d936@13.250.0.144:30317 enode://f2a460e5d5008d0ba8ec0744c90df9d1fc01553e00025af483995a15d89e773de18a37972c38bdcf47917fc820738455b85675bb51b026a75768c68d5540d053@13.250.71.37:30318 enode://f3045792b9e9ad894cb36b488f1cf97065013cda9ef60f2b14840214683b3ef3dadf61450a9f677457c1a4b75a5b456947f48f3cb0019c7470cced9af1829993@13.251.212.212:30319 enode://be14fce25a846bd5c91728fec7fb7071c98e2b9f8f4b710dbce79d8b6098592591ebeebfe6c59ee5bfd6f75387926f9342ae004d6ff8dcf97fc6d7e91e8f41be@3.1.155.129:30320 enode://00e5229f3792264032a335759671996da3714f90f8d19defd0abce4e27515e7e644a76ae19b994f9b28b4d652826fa0766298b60db6df70aa2def7461c50d662@3.1.238.110:30321 enode://369699f91013336e4ecf349aac4a4a6ee3957c7c7577996f9db821013e2e232ef8151e200cc2ab7ea9265121642b05b1cd21640d29e1e4bf8f6af737f353275c@3.1.238.140:30322 enode://ee4c7418336745ed8a54da5fd8b151ade53b0b2a53b8e1d5eecfae483d15f5ff9e440155c47311dc826c44d44dce0080a6246204ed992f1e37d7094df4289169@3.1.238.153:30323]"
INFO[05-14|13:17:13.712] HTTPModules:[personal eth cpc admission net web3 db txpool miner]  Line="cpchain/config.go:188"
INFO[05-14|13:17:13.714] update networkId                              Line="cpchain/config.go:265" networkId=0
WARN[05-14|13:17:13.715] Use account 0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3 as the default account.  Line="cpchain/config.go:228"
INFO[05-14|13:17:13.716] Allocated cache and file handles              Line="database/leveldb.go:32" cache=768 handles=16
INFO[05-14|13:17:13.792] Initialised chain configuration               Line="cpc/backend.go:125" config="{ChainID: 42 Engine: dpor}"
INFO[05-14|13:17:13.792] Initialize remote database                    Line="cpc/backend.go:134" database=Dummy
INFO[05-14|13:17:13.794] Initialising cpchain protocol                 Line="cpc/backend.go:176" network=0 versions="[1]"
INFO[05-14|13:17:13.795] Loaded most recent local header               Line="core/blockchain.go:383" hash=0x2245a3bc74653572f55376011285658da9ba78a5b761c698cb6d03368bb5300a number=398421
INFO[05-14|13:17:13.795] Loaded most recent local full block           Line="core/blockchain.go:384" hash=0x2245a3bc74653572f55376011285658da9ba78a5b761c698cb6d03368bb5300a number=398421
INFO[05-14|13:17:13.795] Loaded most recent local fast block           Line="core/blockchain.go:385" hash=0x2245a3bc74653572f55376011285658da9ba78a5b761c698cb6d03368bb5300a number=398421
INFO[05-14|13:17:13.803] Loaded local transaction journal              Line="core/tx_journal.go:114" dropped=0 transactions=0
INFO[05-14|13:17:13.803] Regenerated local transaction journal         Line="core/tx_journal.go:166" accounts=0 transactions=0
INFO[05-14|13:17:16.072] CpchainService started                        Line="cpc/backend.go:508"
INFO[05-14|13:17:17.121] Unlocked account                              Line="cpchain/cmd_account.go:231" address=0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3
INFO[05-14|13:17:18.168] start participating campaign                  Line="cpc/backend.go:415" campaign=true
INFO[05-14|13:17:18.169] Transaction pool price threshold updated      Line="core/tx_pool.go:558" price=18000000000
INFO[05-14|13:17:18.205] Starting mining operation                     Line="miner/miner.go:105"
INFO[05-14|13:17:25.051] Mining aborted due to sync                    Line="miner/miner.go:76"
INFO[05-14|13:17:25.051] goroutine wait() quit                         Line="miner/engine.go:335"
INFO[05-14|13:17:25.051] Synchronization Started                       Line="syncer/syncer.go:430" local height=398421 peer=a3227b397bc35725 peer.Head=0xd1ec21ff4907b94455011579273a00118a6fbc5dcb7ecd1b6af9febd8b2c74a2 peer.height=398422
INFO[05-14|13:17:25.052] Starting mining operation                     Line="miner/miner.go:105"
INFO[05-14|13:17:25.064] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="0.00 B" elapsed=8ms hash=0xd1ec21ff4907b94455011579273a00118a6fbc5dcb7ecd1b6af9febd8b2c74a2 mgas=0 mgasps=0 number=398422 txCounterAfterStartup=0 txs=0
INFO[05-14|13:17:26.207] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=11067
INFO[05-14|13:17:26.207] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-14|13:17:26.272] found nonce                                   Line="admission/work.go:137" block hash=0x2245a3bc74653572f55376011285658da9ba78a5b761c698cb6d03368bb5300a difficulty=12 nonce=3008 sender=0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3 timeCost(s)=0.0409998
INFO[05-14|13:17:27.198] found nonce                                   Line="admission/work.go:137" block hash=0x2245a3bc74653572f55376011285658da9ba78a5b761c698cb6d03368bb5300a difficulty=6 nonce=62 sender=0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3 timeCost(s)=0.9659969
WARN[05-14|13:17:27.840] Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

** Configuration (please complete the following information):**
 - OS: Windows Server 2016
 - cpchain version 0.2.8

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by NielDS** [comment]
Same error still on 0.2.8 as 0.2.7

Error in claiming campaign Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

Address - 0x85FE91a540a88BeEAd2f18e3AB507537a30Da875

Ubuntu 18.04

**Comment by hvredevoort** [comment]
It may be coincidence, but after opening 2 firewall ports, I could immediately join the campaign.

Using PowerShell in Administrative mode:
# CPChain firewall ports Windows Server 2016
New-NetFirewallRule -DisplayName "CPChain (TCP-In)" -Profile Public -Direction Inbound -Action Allow -LocalPort @("30311","8501") -Group "Masternodes" -Protocol TCP
New-NetFirewallRule -DisplayName "CPChain (UDP-In)" -Profile Public -Direction Inbound -Action Allow -LocalPort @("30311","8501") -Group "Masternodes" -Protocol UDP  

# List firewall group Masternodes
Get-NetFirewallRule -DisplayGroup "Masternodes" | ft -AutoSize

# Remove firewall group Masternodes (remove # in front of cmdlet)
#Get-NetFirewallRule -DisplayGroup "Masternodes" | Remove-NetFirewallRule -Confirm:$false

**Comment by hvredevoort** [comment]
After stopping cpchain, I could not start again without error
Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

**Comment by SanShiner** [comment]
Same here. Tried to start 0.2.8 several times on Ubuntu 18.05 abut always:
Error in claiming campaign                    error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

**Comment by NielDS** [comment]
Additional.

Only get the campaign gas error on the occasions where i think my node selected to be proposer. 

On occasions where not selected there seems to be no error.

**Comment by alex031029** [comment]
Here I post a reply on behalf of telegram user J N

> I do not have Github account, so I post here. #28. I had the same problem as hvredevoort. I adopted his helpful suggestion and opened the firewall ports Inbound and Outbound, and it worked for me. I am sealing. It might be a coincidence, but it works for me.

**Comment by NielDS** [comment]
> Here I post a reply on behalf of telegram user J N
> 
> > I do not have Github account, so I post here. #28. I had the same problem as hvredevoort. I adopted his helpful suggestion and opened the firewall ports Inbound and Outbound, and it worked for me. I am sealing. It might be a coincidence, but it works for me.

On Ubuntu....firewall not enabled

Also ran on windows.......ports open

**Comment by tass21fr** [comment]
I have the same issue with ubuntu 19.04
![image](https://user-images.githubusercontent.com/50399702/57797828-9e15eb80-774b-11e9-951c-a0c26aa93fe6.png)

**Comment by hadox** [comment]
More users are reporting this problem: https://github.com/CPChain/chain/issues/30

**Comment by SeanMacAnAdstair** [comment]
First day using v0.2.8 was fine. Since then I have sealed very few blocks. I get  Error in claiming campaign about 95% of the time.

**Comment by alex031029** [comment]
Port should be not related with campaign. My opinion is that it is a coincidence. But I have reported your situation to all members in our team. 

#30 should be the same issue. Here I close this issue and refer it in #30.
