### ISSUE TITLE
fail to add peer to cpc protocol manager's peer set

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#3]
Its a warning, might be legit, occurs running the 0.2.3 chain.

`WARN[05-08|09:29:37.872] fail to add peer to cpc protocol manager's peer set  Line="cpc/handler.go:323" err=EOF peer.RemoteAddr="3.1.238.110:30321" peer.id=00e5229f37922640`

Running on a local home network, with only 1 machine. The IP of my local machine is not exposed.

In Case thats a legit warning, just close the issue

**Comment by alex031029** [comment]
You can simply omit this warning. We are going to adjust log hierarchy such that it won't raise unnecessary concerns.
