### ISSUE TITLE
since 30h i havent get any block

### ISSUE THREAD

**Issue by mexcpc** [CPChain/chain#30]
Hello,
since arround 30h i havent mined any block. I downloaded last version arround 20h ago and since then im still stuck at 60 blocks. Is that normal?
https://cpchain.io/explorer/address/ac8fd8cb83ac3cd62cae425e0f3f25153a81edf6
Its like this below all the time: like 10times "synchronization started" then "imported new chain segment". and so on.

C:\Users\Adrian\Desktop>cpchain run --datadir ./datadir --unlock ac8fd8cb83ac3cd62cae425e0f3f25153a81edf6 --rpcaddr 127.0.0.1:8501 --port 30311 --mine  --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber
INFO[05-15|18:51:04.065] init validators                               Line="configs/general.go:237" nodes="[enode://2ddfb534019e6b446fb4465742f266d04fae661089e3dac6a4c841ad0fcf5569f8d049203079bb64e20d1a32fc84b584920839a2120cd5e8886744719452d936@13.250.0.144:30317 enode://f2a460e5d5008d0ba8ec0744c90df9d1fc01553e00025af483995a15d89e773de18a37972c38bdcf47917fc820738455b85675bb51b026a75768c68d5540d053@13.250.71.37:30318 enode://f3045792b9e9ad894cb36b488f1cf97065013cda9ef60f2b14840214683b3ef3dadf61450a9f677457c1a4b75a5b456947f48f3cb0019c7470cced9af1829993@13.251.212.212:30319 enode://be14fce25a846bd5c91728fec7fb7071c98e2b9f8f4b710dbce79d8b6098592591ebeebfe6c59ee5bfd6f75387926f9342ae004d6ff8dcf97fc6d7e91e8f41be@3.1.155.129:30320 enode://00e5229f3792264032a335759671996da3714f90f8d19defd0abce4e27515e7e644a76ae19b994f9b28b4d652826fa0766298b60db6df70aa2def7461c50d662@3.1.238.110:30321 enode://369699f91013336e4ecf349aac4a4a6ee3957c7c7577996f9db821013e2e232ef8151e200cc2ab7ea9265121642b05b1cd21640d29e1e4bf8f6af737f353275c@3.1.238.140:30322 enode://ee4c7418336745ed8a54da5fd8b151ade53b0b2a53b8e1d5eecfae483d15f5ff9e440155c47311dc826c44d44dce0080a6246204ed992f1e37d7094df4289169@3.1.238.153:30323]"
INFO[05-15|18:51:04.066] HTTPModules:[personal eth cpc admission net web3 db txpool miner]  Line="cpchain/config.go:188"
INFO[05-15|18:51:04.074] update networkId                              Line="cpchain/config.go:265" networkId=0
WARN[05-15|18:51:04.074] Use account 0xAC8fD8cb83aC3CD62cAe425E0f3f25153a81Edf6 as the default account.  Line="cpchain/config.go:228"
INFO[05-15|18:51:04.081] Allocated cache and file handles              Line="database/leveldb.go:32" cache=768 handles=16
INFO[05-15|18:51:04.200] Initialised chain configuration               Line="cpc/backend.go:125" config="{ChainID: 42 Engine: dpor}"
INFO[05-15|18:51:04.200] Initialize remote database                    Line="cpc/backend.go:134" database=Dummy
INFO[05-15|18:51:04.209] Initialising cpchain protocol                 Line="cpc/backend.go:176" network=0 versions="[1]"
INFO[05-15|18:51:04.216] Loaded most recent local header               Line="core/blockchain.go:383" hash=0x1e75bb03d0d9b2d56f955ec4db3d9a20317c8ed93a5ad2ecff20920e57b94c13 number=408078
INFO[05-15|18:51:04.216] Loaded most recent local full block           Line="core/blockchain.go:384" hash=0x1e75bb03d0d9b2d56f955ec4db3d9a20317c8ed93a5ad2ecff20920e57b94c13 number=408078
INFO[05-15|18:51:04.217] Loaded most recent local fast block           Line="core/blockchain.go:385" hash=0x1e75bb03d0d9b2d56f955ec4db3d9a20317c8ed93a5ad2ecff20920e57b94c13 number=408078
INFO[05-15|18:51:04.246] Loaded local transaction journal              Line="core/tx_journal.go:114" dropped=1 transactions=1
INFO[05-15|18:51:04.249] Regenerated local transaction journal         Line="core/tx_journal.go:166" accounts=0 transactions=0
INFO[05-15|18:51:06.420] CpchainService started                        Line="cpc/backend.go:508"
Unlocking account ac8fd8cb83ac3cd62cae425e0f3f25153a81edf6 | Attempt 1/3
Password:
INFO[05-15|18:51:15.638] Unlocked account                              Line="cpchain/cmd_account.go:205" address=0xAC8fD8cb83aC3CD62cAe425E0f3f25153a81Edf6
INFO[05-15|18:51:16.871] start participating campaign                  Line="cpc/backend.go:415" campaign=true
INFO[05-15|18:51:16.871] Transaction pool price threshold updated      Line="core/tx_pool.go:558" price=18000000000
INFO[05-15|18:51:16.872] Starting mining operation                     Line="miner/miner.go:105"
INFO[05-15|18:51:17.422] Mining aborted due to sync                    Line="miner/miner.go:76"
INFO[05-15|18:51:17.422] goroutine wait() quit                         Line="miner/engine.go:335"
INFO[05-15|18:51:17.422] Synchronization Started                       Line="syncer/syncer.go:430" local height=408078 peer=0f995b236926dc99 peer.Head=0x22910e0313ab82f9175981f10d23a6bcace65bba7d52923e219c4ed33f4b341a peer.height=408097
INFO[05-15|18:51:18.423] Starting mining operation                     Line="miner/miner.go:105"
INFO[05-15|18:51:20.556] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=19 cache="281.34 kB" elapsed=3.055s hash=0x22910e0313ab82f9175981f10d23a6bcace65bba7d52923e219c4ed33f4b341a mgas=4.62 mgasps=1.5118085005916013 number=408097 txCounterAfterStartup=220 txs=220
INFO[05-15|18:51:20.815] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=11336
INFO[05-15|18:51:20.816] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-15|18:51:20.917] found nonce                                   Line="admission/work.go:137" block hash=0x5472fcf0144e25b3c28c3bf842fafd4ddcdea2cd998e0dc64097769387554283 difficulty=12 nonce=436 sender=0xAC8fD8cb83aC3CD62cAe425E0f3f25153a81Edf6 timeCost(s)=0.0070115
INFO[05-15|18:51:22.191] found nonce                                   Line="admission/work.go:137" block hash=0x5472fcf0144e25b3c28c3bf842fafd4ddcdea2cd998e0dc64097769387554283 difficulty=6 nonce=61 sender=0xAC8fD8cb83aC3CD62cAe425E0f3f25153a81Edf6 timeCost(s)=1.2809668
WARN[05-15|18:51:23.141] Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
INFO[05-15|18:51:23.316] Synchronization Started                       Line="syncer/syncer.go:430" local height=408097 peer=0f995b236926dc99 peer.Head=0x35e8587e1642170771ab9980ae022ec825f0f18a7b5c5e64d40b364ad1d1212c peer.height=408098
INFO[05-15|18:51:23.356] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="0.00 B" elapsed=22.998ms hash=0x35e8587e1642170771ab9980ae022ec825f0f18a7b5c5e64d40b364ad1d1212c mgas=0 mgasps=0 number=408098 txCounterAfterStartup=220 txs=0
INFO[05-15|18:51:43.334] Synchronization Started                       Line="syncer/syncer.go:430" local height=408098 peer=c35a01845e5fe7d3 peer.Head=0x85dad6c810d69c2784ea728a394383b643e5b60d00f3f8d1d42995296deb7a9d peer.height=408099
INFO[05-15|18:51:43.371] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="0.00 B" elapsed=23.999ms hash=0x85dad6c810d69c2784ea728a394383b643e5b60d00f3f8d1d42995296deb7a9d mgas=0 mgasps=0 number=408099 txCounterAfterStartup=220 txs=0
INFO[05-15|18:51:53.717] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=c35a01845e5fe7d3 peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:53.733] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=b980387372167f12 peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:53.777] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=a3227b397bc35725 peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:53.786] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=ef8a4ac9b07048aa peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:53.788] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=5960fac611f48724 peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:53.969] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=0054fdd592da259d peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:54.422] Synchronization Started                       Line="syncer/syncer.go:430" local height=408099 peer=0054fdd592da259d peer.Head=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d peer.height=408100
INFO[05-15|18:51:55.094] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="61.91 kB" elapsed=127.995ms hash=0x8a30eee3905da982768ce4087ad2f54a6254195a12ee9375b99b5463017f6a9d mgas=2.241562 mgasps=17.51281881003629 number=408100 txCounterAfterStartup=305 txs=85

**Comment by hadox** [comment]
Hello, 

I have a simular issue. No blocks for the past +24 hours.
Not sure if it's caused by the gas warning:
```
INFO[05-15|17:53:35.008] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="14.80 kB" elapsed=6.380ms hash=0x66e0c1820b87111a0f50d3d01cfed487988fe33dd0b66b32a061dd0b1fc6f146 mgas=0.315 mgasps=49.367384395298906 number=408446 txCounterAfterStartup=258 txs=15
INFO[05-15|17:53:36.031] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=11345
INFO[05-15|17:53:36.031] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-15|17:53:36.055] found nonce                                   Line="admission/work.go:137" block hash=0xaeedecae4be5a6900df691fa29012086f08258ca987116669c97b5db07747ca2 difficulty=12 nonce=642 sender=0xd1317C1ceF7B9BC2C2c62772C2F5F701bAF0fD69 timeCost(s)=0.006290921
INFO[05-15|17:53:36.201] found nonce                                   Line="admission/work.go:137" block hash=0xaeedecae4be5a6900df691fa29012086f08258ca987116669c97b5db07747ca2 difficulty=6 nonce=12 sender=0xd1317C1ceF7B9BC2C2c62772C2F5F701bAF0fD69 timeCost(s)=0.152026209
WARN[05-15|17:53:36.575] Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
```

**Comment by Stef3478** [comment]
Similar issue here. No blocks for the last 18 hrs or so.
I can claim for campaign:
`INFO[05-15|20:02:25.063] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="14.64 kB" elapsed=9.525ms hash=0x0ab18fa826404fcfc8db287f55492687941fcefe9d5e1d11037c8
ee96037c321 mgas=0.273 mgasps=28.661053229665008 number=408493 txCounterAfterStartup=3130680 txs=13
INFO[05-15|20:02:26.077] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=11347
INFO[05-15|20:02:26.077] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-15|20:02:26.262] found nonce                                   Line="admission/work.go:137" block hash=0xccd072e0ecb66a901f63565c8590f632a0db9a49bb292f878cf1100aea26d65d difficulty=12 nonce=9139 s
ender=0xB0320C337737bB468c595Db5c7FA8227FdDAe1Fd timeCost(s)=0.178303098
INFO[05-15|20:02:26.264] found nonce                                   Line="admission/work.go:137" block hash=0xccd072e0ecb66a901f63565c8590f632a0db9a49bb292f878cf1100aea26d65d difficulty=6 nonce=7 sende
r=0xB0320C337737bB468c595Db5c7FA8227FdDAe1Fd timeCost(s)=0.180205776
INFO[05-15|20:02:26.854] Submitted transaction                         Line="cpcapi/api.go:1448" fullhash=0x3976a4dfad8f5839a9bd51c4846a520a77212fde43283cb0833f2cee6aaaab54 recipient=0xb8A07aE42E2902C4133
6A301C22b6e849eDd4F8B
INFO[05-15|20:02:26.854] Claimed for campaign                          CpuBlockNumber=408492 CpuPowResult=9139 Line="admission/admission.go:323" MemBlockNumber=408492 MemPowResult=7 NumberOfCampaignTerms=
3
INFO[05-15|20:02:35.041] Synchronization Started                       Line="syncer/syncer.go:430" local height=408493 peer=5d38053fe43bdbbd peer.Head=0x4aea75146c3e3c338fc6d060937a8fc52b372f300245f72fbf7
c01dffdc39eac peer.height=408494
` 
And sometimes it can't:
`
INFO[05-15|20:20:55.178] Synchronization Started                       Line="syncer/syncer.go:430" local height=408600 peer=5d38053fe43bdbbd peer.Head=0x36f87d46a2cdfb39db63872b651123e51329503ce[561/1959]bee9eb97d7d04 peer.height=408601
INFO[05-15|20:20:55.183] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="13.26 kB" elapsed=8.127ms hash=0x36f87d46a2cdfb39db63872b651123e51329503ce1aff29760bbe
e9eb97d7d04 mgas=0.231 mgasps=28.42097842232565 number=408601 txCounterAfterStartup=3132018 txs=11
INFO[05-15|20:20:56.190] campaign for proposer committee               Line="dpor/consensus.go:221" eleTerm=11350
INFO[05-15|20:20:56.190] Start campaign for dpor proposers committee   Line="admission/admission.go:94"
INFO[05-15|20:20:56.415] found nonce                                   Line="admission/work.go:137" block hash=0xae6e04b0f7f70297c4b3cfdfbb363bc57479f918cb3ad6de98d324474b0e29f2 difficulty=12 nonce=11520 
sender=0xB0320C337737bB468c595Db5c7FA8227FdDAe1Fd timeCost(s)=0.218605539
INFO[05-15|20:20:56.691] found nonce                                   Line="admission/work.go:137" block hash=0xae6e04b0f7f70297c4b3cfdfbb363bc57479f918cb3ad6de98d324474b0e29f2 difficulty=6 nonce=31 send
er=0xB0320C337737bB468c595Db5c7FA8227FdDAe1Fd timeCost(s)=0.494382346
WARN[05-15|20:20:57.241] Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"
`

**Comment by mexcpc** [comment]
Nice to see im not alone. Let's wait for our masters to take a look into it :).

**Comment by Timoess** [comment]
Same here.... havent been able to seal any blocks so far. Do not even see any campains. It is indeed, like 100+ times "synchronization started" then "imported new chain segment". and so on.

![warn rnode](https://user-images.githubusercontent.com/50675565/57808214-2bb10580-7763-11e9-8c90-843509502792.png)

**Comment by mexcpc** [comment]
so im turning of my pc for this night looks like no point to keep mining :/. wasted like 2 days so far.

**Comment by alex031029** [comment]
We have acknowledge multiple complaints that they have not sealed a single block for a long time.  It is highly possible that our refined RPC calculation results in this problem. 

Currently we are investigating and evaluating RPT calculation and election process. And I will keep you updated for this issue.

**Comment by dbchowdary** [comment]
Same issue vultr server not able to secure a single block from more than 24 hours

**Comment by brammb** [comment]
Hi Alex, glad to see that you are working on the issue.
Same problem here, going over 30h without sealing a single block.

**Comment by tass21fr** [comment]
Good. Multiple restarts of the server does not help.

**Comment by brammb** [comment]
Hi Alex,

INFO[05-17|08:29:36.328] campaign for proposer committee               eleTerm=11689
INFO[05-17|08:29:36.328] Start campaign for dpor proposers committee
INFO[05-17|08:29:36.445] found nonce                                   block hash=0x7262008e5eeab726eafa0dabbe327235b7133e083edd7e6b28a5d95ae0ee0327 difficulty=12 nonce=3848 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=0.0759948
INFO[05-17|08:29:37.574] found nonce                                   block hash=0x7262008e5eeab726eafa0dabbe327235b7133e083edd7e6b28a5d95ae0ee0327 difficulty=6 nonce=53 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=1.2049968
INFO[05-17|08:29:38.456] Submitted transaction                         fullhash=0x4e2b587dac7404ad0937e27fa4890b57760cbf646d6eb9392b01d49e0253d62f recipient=0xb8A07aE42E2902C41336A301C22b6e849eDd4F8B
INFO[05-17|08:29:38.457] Claimed for campaign                          CpuBlockNumber=420804 CpuPowResult=3848 MemBlockNumber=420804 MemPowResult=53 NumberOfCampaignTerms=3
INFO[05-17|08:29:45.154] Synchronization Started                       local height=420805 peer=f38cb2bec4472c34 peer.Head=0x9a2f5a58b913f115b21b23fa64671fda781fcc6cf2de48bae9feac76f159a512 peer.height=420806
INFO[05-17|08:29:45.192] Imported new chain segment                    blocks=1 cache="11.13 kB" elapsed=26.004ms hash=0x9a2f5a58b913f115b21b23fa64671fda781fcc6cf2de48bae9feac76f159a512 mgas=0.147 mgasps=5.652824297146285 number=420806 txCounterAfterStartup=256896 txs=7
INFO[05-17|08:29:57.540] Synchronization Started                       local height=420806 peer=f38cb2bec4472c34 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.616] Synchronization Started                       local height=420806 peer=853629f5745dadaa peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.617] Synchronization Started                       local height=420806 peer=0a6fde7294df61b6 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.624] Synchronization Started                       local height=420806 peer=903cf555890daef5 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.633] Synchronization Started                       local height=420806 peer=44eb2b4a478a9d14 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.652] Synchronization Started                       local height=420806 peer=6cb080d2098cf91e peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.675] Synchronization Started                       local height=420806 peer=8aa2c51240fd7b62 peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.730] Synchronization Started                       local height=420806 peer=f01e7ad4e63a063c peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:57.887] Synchronization Started                       local height=420806 peer=f01e7ad4e63a063c peer.Head=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 peer.height=420807
INFO[05-17|08:29:58.210] Imported new chain segment                    blocks=1 cache="333.83 kB" elapsed=659.007ms hash=0x1f38f4f21370ac7360bdb5c66cabf892b4eb8138952eba13f832c074ff274e43 mgas=6.52509 mgasps=9.901388087178358 number=420807 txCounterAfterStartup=256934 txs=38

I can get on the commitee and claim for campaign, but I never seal any blocks anymore.
From update to 2.8 I have sealed 6 blocks.

**Comment by alex031029** [comment]
Hi @brammb , I opened a new issue #36 about your error message, whose cause should be different. Do you mind post your address in #36?

**Comment by alex031029** [comment]
#28 should be the same issue. I merge it into this one.

**Comment by SeanMacAnAdstair** [comment]
I get no more than 10 blocks a day lately. For two days I got nothing. I'm running $96 Vultr VPS, so it cannot be that. I wouldn't even get 10 blocks without restarting the server every 12 hours or so. I am using V0.2.8. I do seal a few blocks if a restart, but I cannot be doing that outside of a test phase.
