### ISSUE TITLE
Blocks are not sealed anymore after getting message "Error in claiming campaign Warning"

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#31]
**Where does the bug occur?**
during the claiming campagne action

**What is your wallet address and your balance?**
If it is too private to answer, you can skip it. 

**Describe the bug**
After i upgraded to a new release (0.2.8) and starting this new release i got the following warning: "Error in claiming campaign Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction""
Since it was a warning i ignored it and let the system run for several hours, but without result, no blocks were sealed.
It looks like the TX part did work, at least this counter did change and gas was taken from my wallet.
Restarting the application did not change anything, still the warning and no blocks

After rebooting the system and starting the application, the warning did not appear anymore
and after about 30 minutes blocks where sealed, more than once

**To Reproduce**
1. upgrade from 2.7 to 2.8 (and if i remember it well, i had the same issue with other release upgrades)
2. check whether you get the Warning about Error in claiming campaign

if error occurred: 
3. stop the application
4. reboot the system
5. start the application
6. log in
7. check whether the warning does not appear
8. wait for 30-60 minutes and check whether the RNode seals blocks
 
**Expected behavior**

**Screenshots**

** Configuration (please complete the following information):**
 centos

**Additional context**
I think it has something to do with uninitiated variables or memory related issues

**Comment by hadox** [comment]
Hello, this issue is already reported: https://github.com/CPChain/chain/issues/30

**Comment by alex031029** [comment]
Hi, #30 is the same issue. I am about close it, you can discuss it in #30
