### ISSUE TITLE
Error in claiming campaign (every 2nd time)

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#32]
**Where does the bug occur?**
After start

**What is your wallet address and your balance?**
0xCF1717B7dC2e17a53B0A9762e86C16d785ab9c3e

**Describe the bug**
Every 2nd time (it looks that this is exactly every 2nd time) i get during claiming capaign this error:
`INFO[05-15|20:20:57.159] found nonce                                   
Line="admission/work.go:137" block hash=0xae6e04b0f7f70297c4b3cfdfbb363bc57479f918cb3ad6de98d324474b0e29f2 difficulty=6 nonce=58 sender=0xCF1717B7dC2e17a53B0A9762e86C16d785ab9c3e timeCost(s)=0.937092098
WARN[05-15|20:20:57.660] Error in claiming campaign                    Line="admission/admission.go:320" error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction" `

** Configuration (please complete the following information):**
 - OS: Ubuntu 18.04 and Arch Linux
 - cpchain version  0.2.8

**Additional context**
an other thing i see often is that i get the message: Successfully sealed new block but its not always true, on the explorer the proposer history it dont change always, just sometimes . (I will do an second issue for that not sure if this Issue are releated to each other #33).

**Comment by alex031029** [comment]
At the first glance it is related to #12 . If I confirm this issue is same as #12 , then I'll close it.

**Comment by alex031029** [comment]
I merge it to issue #12 and close it
