### ISSUE TITLE
Successfully sealed new block --> But proposer History on Explorer doesnt changes

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#33]
**Where does the bug occur?**
chain , explorer

**What is your wallet address and your balance?**
0xCF1717B7dC2e17a53B0A9762e86C16d785ab9c3e

**Describe the bug**
I get often the message in the terminal: "Successfully sealed new block" but its not always true, on the explorer in the proposer history it dont changes the created blocks ( just sometimes ). If i checked the Block which i was creating it shows me on the explorer that somebody else did it. for example the Block 408712 like you can see in the Screenshot should be created by me but on the explorer you will finde somebody else did it.

**To Reproduce**
start 

**Expected behavior**
![issue](https://user-images.githubusercontent.com/24302453/57801702-93ac1f80-7754-11e9-96fe-bf7278568b8a.png)

**Screenshots**

** Configuration (please complete the following information):**
 - Arch Linux
 - cpchain version  0.2.8

**Comment by alex031029** [comment]
This issue looks similar to #26 . I will keep you updated if we have more clues about it.

**Comment by HKet** [comment]
I had this issue this evening also
The software told me that blocks were sealed (3 in total) but no change in Balance and no change in Proposer history

**Comment by alex031029** [comment]
Here I merge this issue to #27 and close it.
