### ISSUE TITLE
[0.2.8] CPChain first time start error

### ISSUE THREAD

**Issue by hadox** [CPChain/chain#34]
**Where does the bug occur?**
Starting cpchain process on VPS

**Describe the bug**
I deleted the cpchain folder on my VPS and started the cpchain application again. It started syncing for +20 minutes and then returned these errors:
```
goroutine 33162 [select, 6 minutes]:
bitbucket.org/cpchain/chain/consensus/dpor/backend.(*RemoteValidator).broadcastLoop(0xc0082925f0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/backend/remote_validator.go:52 +0x251
created by bitbucket.org/cpchain/chain/consensus/dpor/backend.(*Dialer).addRemoteValidator
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/backend/dialer.go:163 +0x32a

goroutine 36269 [select, 1 minutes]:
bitbucket.org/cpchain/chain/consensus/dpor/backend.(*RemoteValidator).broadcastLoop(0xc0004f2b90)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/backend/remote_validator.go:52 +0x251
created by bitbucket.org/cpchain/chain/consensus/dpor/backend.(*Dialer).addRemoteValidator
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/backend/dialer.go:163 +0x32a

```

**Expected behavior**
Sync should continue normally, not crashing with above error

**Screenshots**
See logs

** Configuration (please complete the following information):**
 - OS: Ubuntu 19.04
 - cpchain version: 0.2.8

**Additional context**
Thanks!

**Comment by alex031029** [comment]
We tried several times to reproduce your bug but all failed. And yet I have received similar issue from other participants. This bug seemingly occurs very infrequently. 

We will continue review the code to see how this bug works.

**Comment by hadox** [comment]
FYI: in the TG chat there were reports  from a few users with the same error, but with running nodes. So seems not related to setting up a new node
