### ISSUE TITLE
Multiple Private Keys // Unlocking impossible

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#35]
When having 2 private keys in the datadir/keystore:

`UTC--2019-04-26T14-26-50.359233500Z-AAAA`

`UTC--2019-04-26T14-48-49.150481047Z-BBBB`

Starting the node via:

`./cpchain run --datadir ./datadir --unlock BBBB --rpcaddr 127.0.0.1:8501 --port 30311 --mine --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber`

will lead to:

`WARN[05-16|09:22:23.241] Use account AAAA as the default account.`
`Unlocking account BBBB | Attempt 1/3`

Giving the correct password, it stops with this error:

`goroutine 368 [running]:
bitbucket.org/cpchain/chain/consensus/dpor/backend.(*Handler).AddPeer(0xc0000e4370, 0x1, 0xc0012439e0, 0x1394ba0, 0xc0002879d0, 0x4, 0x80, 0x0, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/backend/handler.go:151 +0x1e4
bitbucket.org/cpchain/chain/protocols/cpc.(*ProtocolManager).handlePeer(0xc000318900, 0xc0012439e0, 0x1394ba0, 0xc0002879d0, 0x1, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/protocols/cpc/handler.go:347 +0x1155
bitbucket.org/cpchain/chain/protocols/cpc.NewProtocolManager.func1(0xc0012439e0, 0x1394ba0, 0xc0002879d0, 0x0, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/protocols/cpc/handler.go:126 +0x5b
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc0002879d0, 0xc0012439e0, 0x1394ba0, 0xc0002879d0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:353 +0x6d
created by bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/peer.go:352 +0x20a

FATA[05-16|09:26:35.038] err when get message authentication coed      err="authentication needed: password or unlock"`

When starting the node with the first AAAA wallet, giving the password, it works as expected.

Therefore I would say, any new wallet that is not the default one (probably 1st by time), wont unlock properly. Seems a bug.

Good luck fixing.

**Comment by alex031029** [comment]
Good point. We've acknowledge this problem, and added it to our TODO list. Thanks for your advice.

**Comment by alex031029** [comment]
We implemented it with a  new flag `--account WALLET_ADDRESS`. It is required in case your `./datadir` directory contains more than one account file.
