### ISSUE TITLE
network issues result in non working RNode

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#39]
**Where does the bug occur?**
The chain

**What is your wallet address and your balance?**

**Describe the bug**
All of a sudden my RNode start complaining about network issues with the following message:
WARN[05-19|07:46:31.293] err when handling sync msg                    Line="cpc/handler.go:406" err="write tcp 45.63.43.247:30311->35.176.27.67:45398: use of closed network connection"

After rebooting the system i got the following error:
WARN[05-19|08:28:15.437] err when handling sync msg         Line="cpc/handler.go:406" err="shutting down"
and
After a restart i got the following error:WARN[05-19|08:31:41.670] err when handling sync msg                    Line="cpc/handler.go:406" err="write tcp 45.63.43.247:30311->108.128.106.221:50122: write: broken pipe"

The RNode was not working anymore i waited for 2 hours but several times i got the err when handling sync message and broken pipe messages

**To Reproduce**
see above

**Expected behavior**
A normal operational system without errors or warnings which is sealing blocks

**Screenshots**

** Configuration (please complete the following information):**
OS : Centos 7
CPChain version 2.8

**Additional context**
To make the system working again i started from a 2.4 snapshot and upgraded this to 2.8 and was able to seal some blocks.
Although the sealing is working, more then once the RNode is failing due to the campaign claim error or gas issue which are already reported

During the day some other people also reported this issue so i am not the only one.

**Comment by alex031029** [comment]
We tried to reproduce the issue, but so far all failed. It would be better if you can offer more detailed log info and steps to reproduce the bug.

**Comment by SeanMacAnAdstair** [comment]
I encountered the same error. After rebooting the server, I still had those warning errors but it then went on to seal three blocks

**Comment by HKet** [comment]
Hi

It is hard to reproduce i am sure!
My RNode was running for a long time (days) and all of a sudden this happened.

I think the best thing you can do is have a look where you do network actions and see whether this part of the code is failure proof, and if not change it if possible.

I am more concerned about how to detect this kind of issues while on main net!
Since the RNode continuous to run and people are not 24/7 looking at the RNode they will not detect it until a couple of hours/days are passed and you see you do not have any income.

Did you think about this, how can this be solved?

Greetings,

Hans Ketelaars

**Comment by alex031029** [comment]
Although we have acknowledged the situation, I am going to close this issue it is several versions behind the current one. If anyone encounters the problem again, please open a new issue describing it. Thanks!
