### ISSUE TITLE
Hacked my balance on the CPChain

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#40]
Hi i added 90400 CPC to my account. Now the big question is the balance part of the RPT? If yes we have a problem, some could get an 5M node in the testNode^^

**What is your wallet address and your balance?**
0xCF1717B7dC2e17a53B0A9762e86C16d785ab9c3e || My Balance: Whatever i want i guess ^^

Look on my Address and the Blocks:
from address 0xb3801b8743DEA10c30b0c21CAe8b1923d9625F84--> Blocks: 440518, 440511, 440502, 440498, 440491
from address 0xC6bFd405A99a39Fa06f3cf0F568c3A2A40c29882--> Block: 441736
from address 0xc05302AceBd0730E3A18A058d7d1CB1204C4a092 --> Block: 441667
etc.
.
.
.

![Bildschirmfoto von 2019-05-19 23-40-41](https://user-images.githubusercontent.com/24302453/57988507-b198bd80-7a8f-11e9-9f43-3a849bece7f3.png)

**Comment by alex031029** [comment]
Aha! You are the first, as far as I know, find and utilize these special accounts in our repo. Of course they can only be used in private chain or Mainnet test.

**Comment by kbaf** [comment]
Nice find, not a real hack, but still funny. :-) 

:+1:

**Comment by Mateus224** [comment]
Exacactly, but if i do change my Balance do it influence it my RPT? Because its not fair to the other? Or is the Balance RPT wroten at the beginning as we run the smart contract?

**Comment by alex031029** [comment]
Yep, you are right. You gained a little advantage by adding your balance, although it won't change too much. I think you have drained all their balance.
