### ISSUE TITLE
Website showing zero balance

### ISSUE THREAD

**Issue by SeanMacAnAdstair** [CPChain/chain#41]
Hi there, 

**Where does the bug occur?**
Explorer

**Describe the bug**
Quantities for transactions and blocks are shown, but the balance is zero

**Expected behavior**
The appropriate balance

**Comment by SeanMacAnAdstair** [comment]
No it is back to my starting balance!

**Comment by alex031029** [comment]
Yep, we recalculated balance once, when we updated our smart contract. 
I am going to close this issue. But if you encounter this problem once gain, feel free to open another one.
