### ISSUE TITLE
Error="failed to estimate gas needed"

### ISSUE THREAD

**Issue by brammb** [CPChain/chain#44]
Machine: VPS, 6vCPU's, 8gb RAM, Windows Server 2019.

Adress: 0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373

INFO[05-20|22:04:36.260] campaign for proposer committee               eleTerm=12478
INFO[05-20|22:04:36.260] Start campaign for dpor proposers committee
INFO[05-20|22:04:36.299] found nonce                                   block hash=0x4adc797c25716e10805b4c72b1a4ec1e8d5cd5c6d7d2a9ea99356dd124399aba difficulty=12 nonce=15 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=0
INFO[05-20|22:04:37.953] found nonce                                   block hash=0x4adc797c25716e10805b4c72b1a4ec1e8d5cd5c6d7d2a9ea99356dd124399aba difficulty=6 nonce=82 sender=0x116143Ba590b7a7dc75f276243Da0A4bfC0Ae373 timeCost(s)=1.6539837
WARN[05-20|22:04:38.651] Error in claiming campaign                    error="failed to estimate gas needed: gas required exceeds allowance or always failing transaction"

**Comment by millennium-falcon42** [comment]
@jsyqrt As we've mentioned, please add more log info to the program.

**Comment by alex031029** [comment]
I am going close it due to the lack of log info. Please open a new issue if you encounter the problem again along with sufficient log information. Thanks!
