### ISSUE TITLE
Adding library in the documation.

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#45]
**Is your feature request related to the chain, the wallet, the console, the explorer, or other aspect?**
Smart Contract

**Is your feature request related to a problem? Please describe.**
I had problem to run / compile out of the box the greeterContract.

**Describe the solution you'd like**
Add on the documentation site:
```console 
sudo apt-get install libz3-dev 
```
 https://docs.cpchain.io/quickstart/quickstart.html#smart-contract-examples

**Comment by alex031029** [comment]
Actually we have one in FAQ as https://docs.cpchain.io/faq/faq.html#message-error-while-loading-shared-libraries-libz3-so-4-pops-when-running-solc

But I can point it out in quick start. Thanks !
