### ISSUE TITLE
Collect info about rnode hardware and software configuration

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#46]
Related to chain

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to explain why rnodes perform better over other rnodes. 

**Describe the solution you'd like**

Although the hardware specifications do not yet fully count in RPT (low threshold for hardware is set), it would be beneficial if some score could be calculated and some properties are logged/collected:
- processor manufacturer
- processor speed in Ghz
- number of (virtual) cores
- memory (RAM)
- disktype
- disksize
- Internet upload speed
- Internet download speed
- operating system type
- operating system version
- virtual/physical (if this can be determined)
- IP Address

**Describe alternatives you've considered**

Allow code to push specifications to the CPChain management servers

**Additional context**

**Comment by kbaf** [comment]
My VPS hoster doesn't give accurate CPU info via the linux terminal, they have changed the display of the CPU to just 1 (old) cpu, while in fact the whole network is updated to new XEON cpu's, but because not all CPU's are the same they have changed the display to just one to prevent from questions like 'why am i running on this CPU today while i yesterday had another one'.

So, i cannot give you any other info than i am using 2 VCPU's, but my usage never exceed 50% when having occasional spikes, regular is 1.5% for me.

**Comment by alex031029** [comment]
It is impossible for us to collect the detailed hardware and software configurations via cpchain binary file. All we can do is to launch a process (which is AC) evaluating the specs according its termination time. Any computer that can terminate within a time threshold is qualified as a capable machine running a node. 

As for @kbaf 's case, it may lead to situation where VPS satisfies AC minimum requirement but fluctuate to low specs when sealing blocks. It is just my suspicion.

**Comment by hvredevoort** [comment]
ok thanks for explaining, it will be difficult in this case to evaluate how to improve reputation. Perhaps you could use IP address / location to show a minimum of information of rnodes as distributed across the globe.

**Comment by alex031029** [comment]
That's right. We are considering to bring a heatmap showing the geographical distribution of all CPChain nodes, although it would be distorted since a large amount of nodes are deployed in VPS or other cloud servers. But, it is still a nice illustration showing the vitality of CPChain community.

**Comment by hvredevoort** [comment]
When can we expect the heatmap?

**Comment by alex031029** [comment]
Heatmap is cool, I didn't think it can be implemented in a near future, since we get a lot of things to do and a fancy heatmap cannot be privileged.
