### ISSUE TITLE
RPT Smart contract vs. Documentation

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#47]
In the documentation is written, that the RPT is calculated on the NUMBER of transactions but in the solidity contract the name of the lib. function is called getTxVolume. 

So is the RPT calculated based on the VOLUME or the NUMBER of transactions? I cant hardly understand this code. Maybe you can explain this function?

    function getTxVolume(address addr, uint256 blockNum) internal view returns (uint256 b) {
        assembly {
            let p := mload(0x40)
            mstore(p, addr)
            mstore(add(p, 0x20), blockNum)
            if iszero(staticcall(not(0), 0x68, p, 0x40, p, 0x20)) {
                revert(0, 0)
            }
            b := mload(p)
        }
    }

**Comment by Mateus224** [comment]
According to the solidity docs, mload(p) returns mem[p..(p+32)]. mload(0x40) then returns the value stored in memory at address 0x40. In solidity, address 0x40 is reserved as a free memory pointer. The content of address 0x40 is the next free memory address.

mstore(p,v) sets mem[p..(p+32)] := v. In other words, mstore stores the value v at the memory address p. p..(p+32) means the entire word or block of memory at p is filled by v.

So we store in the first free memory 0x40 the adress the in the next 32 to bytes we store the blockNumber --> mstore(add(p, 0x20), blockNum) 
and the return is b= mload(p) and this is still the the address??

and what we are doing here: 
staticcall(not(0), 0x68, p, 0x40, p, 0x20)

?

**Comment by alex031029** [comment]
Ah, the `getTxVolume` function is deprecated. The first version RPT calculation is name as `primitive contract` which is written on solidity, which turns out to be extremely slow. Thus, we abandoned it and adopt Golang to implement RPT calculation as well as election.

**Comment by Mateus224** [comment]
okay that explains much because i was confused why everything is double ^^ Do you can say me where and how you read from the blockchain the Transaction Data?

**Comment by alex031029** [comment]
In our explorer, the transaction history is continuously added to our local Mango DB by overseeing a civilian node which is keeping synced with the chain. Otherwise, I think you should traverse the whole chain to collect all data you need.
