### ISSUE TITLE
Getting real world data into the Smart Contract (SC) with Oraclize

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#48]
Hi there,

**Is your feature request related to the chain, the wallet, the console, the explorer, or other aspect?**
Chain --> Smart Contracts

**Is your feature request related to a problem? Please describe.**
I m writing a SC and i want to put real world data into the SC. 

**Describe the solution you'd like**
For that i need Oraclize which is a service on ethereum and gives you API to get real Data from World Wide Web and from other Blockchains into your smart contract. It secures the data transports from the Web into the blockchain in this way that it cant be manipulated. So if i write a smart contract e.g. for betting and i use an Internet side then i can just put the websites API directly into solidity over oraclize and it will guarantee that this smart contract will use only the informations from this side and it cant be manipulated. 
Everybody can read the SC and trust then that the programmer or who ever cant manipulate the data that they are really comming from an other Blockchain or from this Website. its an REAL important feature for every Blockchain. And not hard to realize it. Oraclize provides a utility for this,  you can use the ethereum-bridge. Link to a guide: https://ethereum.stackexchange.com/questions/11383/oracle-oraclize-it-with-truffle-and-testrpc/11389#11389

**Comment by alex031029** [comment]
Hi Meteus,

I personally have discussed with my tech leader on this issue. Although he concurred that it was a good feature, at the current stage we had no plan to implement it. Thus, I am going to close this issue. 

In the future, it is still possible for us to bring this feature to CPChain.
