### ISSUE TITLE
Sending transactions

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#50]
Hi there, 

**Where does the bug occur?**
During a loop of sending of transaction

**Describe the bug and Reproduce**
when i m sending in a loop transactions like every 20seconds or something like that i get:
ValueError: {'code': -32000, 'message': 'known transaction: 455a6c5783dc40338cdace5a16acdc423f05469696d77ff576dcc88145facc8a'}

If i do a loop over 1min i can send more transactions before i get this Error.

**Expected behavior**
I would expected that i dont get an error, if somebody will do in the future on the mainchain a loop of transactions he/she should could do it because he /she will pay gas for that, so DDOS should be not the problem or? 

 - OS: Ubuntu 18.04
 - cpchain version: 0.2.9

**Comment by alex031029** [comment]
So you are sending transaction via APIs? It is because you send two or more identical transactions (using same nonce). Thus, the second (third, 4th,...) cannot be added into the transaction list.

**Comment by Mateus224** [comment]
Yes via APIs. How can i change the nonce? I changed in 
    # set chainId to None if you want a transaction that can be replayed across networks
    tx_dict = dict(
        type=0,
        nonce=web3.cpc.getTransactionCount(from_addr),
        gasPrice=web3.cpc.gasPrice,
        gas=90000,
        to=to_addr,
        value=10,
        data=counter,
        chainId=42,
    )
the data. But then i get after 2-3 transactions this Error: 
ValueError: {'code': -32000, 'message': 'replacement transaction underpriced'}
How can i solve this?
