### ISSUE TITLE
Minor issue: on RNode Tx overview page

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#51]
**Where does the bug occur?**
RNode Tx overview page

**What is your wallet address and your balance?**
not relevant

**Describe the bug**
On the RNode Tx overview page you sentenced "Latest 25 txs from a total of XXX transactions".
Since this page supports a paging mechanism, this statement is not correct if your NOT on the first page. 

**To Reproduce**
Open the RNode Tx overview page

**Expected behavior**
Don't talk about the latest 25 just show the total. 

**Screenshots**
![Schermafbeelding 2019-05-23 om 19 24 39](https://user-images.githubusercontent.com/24922860/58273513-2a01c600-7d91-11e9-95c0-a6f4164fd0d0.png)

** Configuration (please complete the following information):**
MacOs

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
Make sense! I have assigned my teammate to refine it.

**Comment by alex031029** [comment]
![image](https://user-images.githubusercontent.com/2452221/58368842-0d969280-7f25-11e9-9a09-a2bdb6f1733a.png)
Nailed it!

**Comment by HKet** [comment]
Great!

I have seen it, however still a small remark i would say:

Showing transactions x to y from....

Instead of Latest...

Grt,
Hans Ketelaars

Verstuurd vanaf mijn mobiele telefoon

**Comment by alex031029** [comment]
hmm, I think you are right. "Latest" also sounds weird to me. I have assigned my teammate to delete the word "latest"
