### ISSUE TITLE
Several impeached blocks with 2.9

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#52]
**Where does the bug occur?**
in explorer

**What is your wallet address and your balance?**
0x28E8FbACC91e01D5F111017C0fC969334c7FDE87
345000

**Describe the bug**
After running for several hours without problems all of a sudden the system created 9 impeached blocks in 2.5 hours.
In this period several other people did also notify this

**To Reproduce**
????

**Expected behavior**
No impeached blocks

**Screenshots**

** Configuration (please complete the following information):**
 - centos 7
 - cpchain version 0.2.9

**Additional context**
Since i am running a vps from vultr whom guarantee a high uptime i don't think it has anything to do with a network issue on my machine.
My machine is located in Amsterdam and i had a look at this server but no issues reported

**Comment by HKet** [comment]
Hi there,

Today i had during 1 hour only impeached blocks, very strange
![image](https://user-images.githubusercontent.com/24922860/58498277-04ecc900-817e-11e9-9c32-e1dda1b0831a.png)

and all of a sudden 1 or 2 impeached blocks between all succesfull ones
![Schermafbeelding 2019-05-28 om 19 25 25](https://user-images.githubusercontent.com/24922860/58498523-80e71100-817e-11e9-9532-bcce90b8c4fb.png)
![Schermafbeelding 2019-05-28 om 19 26 48](https://user-images.githubusercontent.com/24922860/58498562-96f4d180-817e-11e9-95e7-8652ff6d1ee5.png)


The strange  thing is that some remain visible in the overview while others are not.

**Comment by alex031029** [comment]
Sorry that I didn't reply this issue on time. Since the current version is already 2.11 and this issue is obsolete,
I am going to close this issue.
