### ISSUE TITLE
BUG : Fusion generates invalid JSON data

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#53]
When i use Python 3.6 with cpc-fusion on CentOS i get invalid JSON data returned.

The JSON data contains single quotes where it should have double quotes, the returned data is not suitable to process with another application because of this without replacing the single quotes with double ones, but the original JSON data is not in valid format. 

This is the script i am running (following the example given by the documentation) but instead of printing to display, the output is printed to a file:

from cpc_fusion import Web3
from cpc_fusion.middleware import geth_poa_middleware

cf = Web3(Web3.HTTPProvider('http://127.0.0.1:8501'))

json = (cf.cpc.getRNodes)

with open("/path/to/file/data.txt", "w") as text_file:
    print(json, file=text_file)
 

*********************************************************

And this is the result of such a query:

[{'Address': '0x9e61732d0b1c1674151a01ac0bba824c5b6258fb', 'Rpt': 5805, 'Status': 1}, {'Address': '0xaa6cf4f0338e04a40709dfa3c653efc6cd9e65c9', 'Rpt': 6925, 'Status': 0}, {'Address': '0x7170f578ca82897375f009ddea399df08f31bcff', 'Rpt': 6355, 'Status': 1}, {'Address': '0x4c61559aa727380e3fa516b6a7ae397b87ec2384', 'Rpt': 6065, 'Status': 0}, {'Address': '0xc5b481361bbcabb96ed0c835cee69b471449f49c', 'Rpt': 6305, 'Status': 1}, {'Address': '0x6e7fdba0fe5067a25a3cf1df90429e3c949411e3', 'Rpt': 5985, 'Status': 1}, {'Address': '0x27e81a296f5b80d319d2f3008f2d5998530e79e4', 'Rpt': 5335, 'Status': 0}, {'Address': '0x52e584b4fba8688eb7edcabb18e65661a99acc67', 'Rpt': 6185, 'Status': 0}, {'Address': '0x030352bba36c0c7cec8669f64a26d96d5d679bdb', 'Rpt': 6035, 'Status': 0}, {'Address': '0xf561ebb8a40814c1cf3cc0a628df5a1bd7663b26', 'Rpt': 6335, 'Status': 0}, {'Address': '0xca8e011de0edea4929328bb86e35daa686c47ed0', 'Rpt': 6335, 'Status': 0}, {'Address': '0xcc9cd266776b331fd424ea14dc30fc8561bec628', 'Rpt': 6585, 'Status': 1}, {'Address': '0x70ec36d53d4424eeb3b700f82369b966f94bc336', 'Rpt': 6870, 'Status': 1}, {'Address': '0xd04cb4bcaa288d79a7ab577767d9ac24b27f8a4f', 'Rpt': 6820, 'Status': 1}, {'Address': '0x28e8fbacc91e01d5f111017c0fc969334c7fde87', 'Rpt': 5220, 'Status': 0}, {'Address': '0xe78a4c06a14e3ebf66218202e0edc3ee6d267b88', 'Rpt': 6520, 'Status': 1}, {'Address': '0xfe32592fa0700d15e8325d531f12201b21c154f5', 'Rpt': 4720, 'Status': 1}, {'Address': '0x717374a72320f7aa256e051c77435282a456ceaf', 'Rpt': 6770, 'Status': 1}, {'Address': '0xd2c05c0c0063f0debcd0350191fcd66535c7bb44', 'Rpt': 5170, 'Status': 1}, {'Address': '0x21ace0a094d98b34108a8cf583f2a379ec9ac3ee', 'Rpt': 5120, 'Status': 1}, {'Address': '0x4dff92dcd046fcd75a62ea37d9c05c1c988b37d3', 'Rpt': 6220, 'Status': 1}, {'Address': '0x560d1c7be6281e978efc73dfa2c0f17332d56c61', 'Rpt': 7120, 'Status': 1}, {'Address': '0x73e5aff62fbd11e4b2a531883c0e775beb45b694', 'Rpt': 3270, 'Status': 1}, {'Address': '0x7d86efc308a3b0bfe8c919b41bc0ca6bb1d9fbf1', 'Rpt': 4370, 'Status': 1}, {'Address': '0x124634f589d73a0e524eb3b177ee449157ef3860', 'Rpt': 2870, 'Status': 1}, {'Address': '0xd1317c1cef7b9bc2c2c62772c2f5f701baf0fd69', 'Rpt': 2570, 'Status': 1}, {'Address': '0x116143ba590b7a7dc75f276243da0a4bfc0ae373', 'Rpt': 5470, 'Status': 1}, {'Address': '0x761196a0030cd83ba0aa850d5c14398ef4f80d7f', 'Rpt': 3320, 'Status': 1}, {'Address': '0xb0320c337737bb468c595db5c7fa8227fddae1fd', 'Rpt': 3670, 'Status': 1}, {'Address': '0x8cddaa9c802eb4926a7cb39ee8cbeda6800d5412', 'Rpt': 4820, 'Status': 0}, {'Address': '0x67ebab62c3b01a80d48dc41b9bc510f5a4582807', 'Rpt': 6670, 'Status': 1}, {'Address': '0x0c42ceae2921b3a8c390e3c38a2c126730761911', 'Rpt': 5720, 'Status': 1}, {'Address': '0xb592467450c6fa00d6f3505fc862ecd170f38734', 'Rpt': 5020, 'Status': 1}, {'Address': '0x0ddb0f3af8595754e8d913f16a0605d10f6fb6ee', 'Rpt': 1970, 'Status': 1}, {'Address': '0x295226d148533706caee6f94917b4134f53c1180', 'Rpt': 4570, 'Status': 1}, {'Address': '0x1d93a6d7c9169b06f4c5fb8f9307c69192865ce3', 'Rpt': 6770, 'Status': 0}, {'Address': '0x0a799b3dae89b7c2d7f9707c38a6a91914d0097f', 'Rpt': 5070, 'Status': 0}, {'Address': '0x4b84c00859bae7c3d8afaf1048f8135ea09eb3e3', 'Rpt': 4670, 'Status': 1}, {'Address': '0xed952d8617a1502078493f2f7a28e8a182e7b381', 'Rpt': 2970, 'Status': 1}, {'Address': '0x41c6b9c149e0fe73e361d9c1dd8ff3ff7e4c313c', 'Rpt': 2770, 'Status': 1}, {'Address': '0x288f342294f1735c3f7b8b54f2566845dac99c15', 'Rpt': 2470, 'Status': 0}, {'Address': '0xb798d20126daa11f0f72ddb85db0417f6ab10454', 'Rpt': 2620, 'Status': 1}, {'Address': '0x2c1ddb925c5b574f39b0641e07dea16488a1a9f7', 'Rpt': 3420, 'Status': 1}, {'Address': '0x07071106dad0dc67da2ffb2339f8539c8df06671', 'Rpt': 2320, 'Status': 1}, {'Address': '0x2d04e39bce5c5cf71ed6c49a31c7f383433e61d1', 'Rpt': 3020, 'Status': 1}, {'Address': '0x85fe91a540a88beead2f18e3ab507537a30da875', 'Rpt': 3220, 'Status': 1}, {'Address': '0x36f252fdd1eedef107c17d834cef9d213743cff7', 'Rpt': 3720, 'Status': 1}, {'Address': '0x522367812b8aed7458600f8b887355e3cb590713', 'Rpt': 2185, 'Status': 1}, {'Address': '0xbc4199ff6e0ca0a5f6fcc055ba9d1842fafe8370', 'Rpt': 4420, 'Status': 1}, {'Address': '0x2ddc9afd10194631924ea5b8cd7fc03b4b6ccf51', 'Rpt': 6820, 'Status': 1}, {'Address': '0x8a5508d8e60ac2c2b4897d30e3d3407fd42f7720', 'Rpt': 2470, 'Status': 1}, {'Address': '0xcf1717b7dc2e17a53b0a9762e86c16d785ab9c3e', 'Rpt': 4220, 'Status': 1}, {'Address': '0xfdf2f92541d8a78abc28f173be4578ccef716adc', 'Rpt': 2420, 'Status': 1}, {'Address': '0xa21c574cbaa8b1c6f5bffa3342cead5c16792933', 'Rpt': 3120, 'Status': 1}, {'Address': '0xac8fd8cb83ac3cd62cae425e0f3f25153a81edf6', 'Rpt': 1720, 'Status': 1}, {'Address': '0xe325a1843e4f50d6ac8fd39ab2774cef6e70c200', 'Rpt': 3070, 'Status': 1}, {'Address': '0x2ec1d0d103c1f78d85419b7afdff64546852fd30', 'Rpt': 4770, 'Status': 1}, {'Address': '0x4e3a3b8e367490a5262481894358138a637155cf', 'Rpt': 3620, 'Status': 1}, {'Address': '0xcdc888799762436da4d4c9b171ae2a1008cde986', 'Rpt': 2020, 'Status': 1}, {'Address': '0x6026ab99f0345e57c7855a790376b47eb308cb40', 'Rpt': 5370, 'Status': 1}, {'Address': '0xe64501211d47f1adebc1b2cbe8cd016348e09c35', 'Rpt': 4270, 'Status': 1}, {'Address': '0xcde2c989bd0ae629bbbd9b7518178aff3e25e902', 'Rpt': 4220, 'Status': 1}, {'Address': '0xc07d41645eb0adee30cf8f1952f32e99879a897c', 'Rpt': 3870, 'Status': 1}, {'Address': '0xaacfc9371f98dd7f75ada6707e0d1185c76a6f31', 'Rpt': 4120, 'Status': 1}, {'Address': '0x86c9699566647cd7db6906447856198c87600f99', 'Rpt': 3920, 'Status': 1}, {'Address': '0xe8ccc4ea5406aa42ca655562fbe61c775292ff0b', 'Rpt': 4070, 'Status': 1}, {'Address': '0x8ae4da69402d6d5e11949e11f6bc947a992d8e1e', 'Rpt': 3770, 'Status': 1}, {'Address': '0xdd83641d9b1aa4d9096ba90b4fa2788d4dd061b2', 'Rpt': 3570, 'Status': 1}, {'Address': '0x7d83f7682fddcfbb2ebb82975ef2fd0a3994e2ab', 'Rpt': 2120, 'Status': 1}]

**Comment by alex031029** [comment]
Sorry that I didn't get your point. In python, single quotes and double quotes have no difference. 

I have also wrote a script using fusion API and crawl data from cpcstats written by you, which is to investigate the relationship between RPT and number of mined blocks in 24H. I believe you have seen it before in the telegram group.
