### ISSUE TITLE
it is not RNode, cannot participate campaign. Not enough money to become RNode

### ISSUE THREAD

**Issue by jaggedsoft** [CPChain/chain#54]
![image](https://user-images.githubusercontent.com/4283360/58337563-5a576c00-7e46-11e9-95fc-48d2b094d588.png)

cpchain public key: e87bc9724b210f07f962e2ec1f8aa8ea41060d68
cpchain eth address: https://etherscan.io/address/0x0D1c87a87eD9503D5139D6ed29530865B8a938bA

![image](https://user-images.githubusercontent.com/4283360/58337662-97bbf980-7e46-11e9-98a4-e0030b0a48ea.png)

**the block explorer only shows cpchain leaving my account**
https://cpchain.io/explorer/address/e87bc9724b210f07f962e2ec1f8aa8ea41060d68

**Comment by jaggedsoft** [comment]
I have been holding these tokens since the private presale. I just want to make sure this is working properly.

**Comment by alex031029** [comment]
Sorry for replying you late.

It is an old issue as #20 . In that version, we updated smart contract which resulted in your case. And I have checked your node just now, your last sealed block is 10 hrs ago. Thus, your problem should be fixed.
