### ISSUE TITLE
broken pip after sending very fast transactions--> coud be used to hack the network?

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#56]
**Where does the bug occur?**
the chain

**What is your wallet address and your balance?**
0xcf1717b7dc2e17a53b0a9762e86c16d785ab9c3e

**Describe the bug**
After I was sending in a fast loop thousands of transactions i get this error (screenshot) and even a restart didnt help.

**To Reproduce**
Run very fast many transactions in a loop

**Expected behavior**
No Error

** Configuration (please complete the following information):**
 -  Ubuntu 18.04
 - cpchain version 0.2.9

![Bildschirmfoto von 2019-05-26 22-35-36](https://user-images.githubusercontent.com/24302453/58386994-098f7100-8008-11e9-86bd-a0bd4a5c4142.png)

**Additional context  1**
Earlier I was connected to the node: 'http://3.1.81.79:8501' and i made 10k transactions in a loop. Now i cant connect with this  Node.  If i would know all IP addresses of the RNodes i could shut down them one after the other, so that nobody can connect to the network?

**Additional context  2**
When i m running it veeeery fast i get this error SOMETIMES, too:
ValueError: {'code': -32000, 'message': 'known transaction: ed655f363abd955d17a9089c10b0eba2d7f25735bb5289062b5c9dd23da0ab63'}

Even i have a changing "nonce"

What i can do to solve it?

**Comment by alex031029** [comment]
I remembered that you have test a loop sending transaction in #50 . Could you tell me how you modified nonce for each iteration of sending transaction.

**Comment by Mateus224** [comment]
Nothing special you told me the nonce is like an ID and I m changing just the number so that i can put more then one transaction can be added into the transaction list.:
`
 counter=web3.cpc.getTransactionCount(from_addr)
 while 1:
    tx_dict = dict(
        type=0,
        nonce=counter,
        gasPrice=price,
        gas=90000,
        to=to_addr,
        value=1000000000000,
        data=counter,
        chainId=42,
    )
    web3.toHex(signed_txn.rawTransaction))
    print(web3.cpc.sendRawTransaction(signed_txn.rawTransaction)
    counter=counter+1
`

But if i do it really fast and i m adding like 40 transactions / Second i get this error:
ValueError: {'code': -32000, 'message': 'known transaction: ed655f363abd955d17a9089c10b0eba2d7f25735bb5289062b5c9dd23da0ab63'}

And the other thing with the broken pip happens after stopping sending transactions

**Comment by alex031029** [comment]
Your way to modify nonce is okay. It simply is because your too quick transaction request beyonds our designed tps (transaction per second) limit. Please `sleep` a little while between two consecutive transactions :D
