### ISSUE TITLE
CPC rewards after RNode public test phase should be split evenly across participants

### ISSUE THREAD

**Issue by berndfue** [CPChain/chain#58]
Dear CPChain team,

See enclosed my request "CPC rewards after RNode public test phase should be split evenly across participants".
Keep up the good work :-)

**Is your feature request related to the chain, the wallet, the console, the explorer, or other aspect?**
No - only to the RNode public test phase

**Is your feature request related to a problem? Please describe.**
A lot of us had/have varying performance up to not working / reward generating nodes from time to time without our fault at all wile at the same time the CPChain RNodes took/take a lot of blocks/rewards.

**Describe the solution you'd like**
Since (I guess) everyone participating to the test is using performant hardware (I for myself have an i9 9900k with 64GB RAM, 2TB NVMe SSDs and a 1GBit/s network) it would be fair and encouraging from your side to split the RNode public test phase CPC rewards which will be rewarded after the test phase evenly across all participants.

Thanks & best wishes,
Bernd

**Comment by osheajinro** [comment]
Hey mate, thanks for the concern. Tbh, the issue has been raised from several other community participants as well. For this season's test, we will make an assessment at the end of the term, if the community cannot get the full amount of reward. We will make some compensation plans to ensure the community can get the reward.  Cheers.

**Comment by alex031029** [comment]
@osheajinro is Wayne of CPChain Team. He answers questions and issues about marketing here.

**Comment by berndfue** [comment]
Hi Wayne @osheajinro !

Awesome to hear from you on this direct way.
And also your answer is awesome to me since my aim is to have it as fair as possible to not see some flame wars starting after we have concluded the test ;-)
In my opinion participants should not get the amount of mined blocks / a share of the rewards based on the mined blocks, since those can vary greatly because some people might have some issue and mine nothing (which is great! it's a test - without those issues you would't get data needed), while some others find ways which give their reputation a great boost helping them to mine more (which is also a great thing - it's a test and people should find this kind of stuff!).
Still, this should not have any influence on the rewards everyone gets tbh - for me everyone has provided their energy, skills and hardware to the fullest to this test (& some maybe more - see for example Erwin with cpcstats - but those guys should already get bug bounties etc.) so everyone should get the same amount of CPC at the end (for me not even their locked amount counts FULLY because right now it's not more than monopoly CPC :-) and everyone contributed the same. I said fully with a purpose - I think it should count but more or less only as some kind of staking rewards like you gave everyone in the former lock up seasons)

Cheers,
Bernd

**Comment by alex031029** [comment]
Hi Bernd,

Thanks for your relay. Wayne is not a developer so he seldom check this page. 

I concur that everyone has contribute a lot to our chain testing and we appreciate your enthusiasm and time in the chain. In my humble opinion, the reward is proportional to the number of mined blocks are rational. Despite that the mining process involving multiple factors, like luck and server specs. I think an uneven distribution is a better incentive for all participants.

**Comment by berndfue** [comment]
Hi Yanchen!

 

Actually how you did the distribution was pretty perfect :-)

Thanks for this!

 

Cheers,

Bernd

 

Gesendet: Dienstag, 25. Juni 2019 um 08:38 Uhr
Von: "Yanchen" <notifications@github.com>
An: CPChain/chain <chain@noreply.github.com>
Cc: berndfue <bernd.fuerlinger@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [CPChain/chain] CPC rewards after RNode public test phase should be split evenly across participants (#58)


Hi Bernd,

Thanks for your relay. Wayne is not a developer so he seldom check this page.

I concur that everyone has contribute a lot to our chain testing and we appreciate your enthusiasm and time in the chain. In my humble opinion, the reward is proportional to the number of mined blocks are rational. Despite that the mining process involving multiple factors, like luck and server specs. I think an uneven distribution is a better incentive for all participants.

**Comment by alex031029** [comment]
Thanks for your understanding :D
