### ISSUE TITLE
WARN sync timeout

### ISSUE THREAD

**Issue by SeanMacAnAdstair** [CPChain/chain#59]
**Where does the bug occur?**
The chain

**Describe the bug**
Warnings appear saying 'sync timeout' 

**Screenshots**
WARN[05-29|11:26:59.575] sync timeout                                  Line="syncer/syncer.go:603"
WARN[05-29|11:28:19.535] sync timeout                                  Line="syncer/syncer.go:603"
WARN[05-29|11:29:19.549] sync timeout                                  Line="syncer/syncer.go:603"

** Configuration (please complete the following information):**
 - OS: Windows Server 2016
 - cpchain version: 2.10

**Additional context**
Too early to say if it prevents sealing.

**Comment by kbaf** [comment]
I have them too.

CentOS 7, and 0.2.10

**Comment by HKet** [comment]
on my machine as well

CentOS 7, 0.2.10

**Comment by edat10000** [comment]
I had them too with v0.2.11

**Comment by hvredevoort** [comment]
Ubuntu 19.04 too, synched with 57 nodes and get this error repeatedly on first sync
