### ISSUE TITLE
panic: runtime error:invalid memory address or nil pointer dereference  in 0.2.10

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#60]
**Where does the bug occur?**
RNode software

**What is your wallet address and your balance?**
If it is too private to answer, you can skip it. 

**Describe the bug**
While running for several hours al of a sudden the RNode crashed with the following message:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbe6603]

The logging just before the crash and the crash itself:
NFO[05-30|03:20:09.701] Synchronization Started                       Line="syncer/syncer.go:430" local height=521777 peer=2c8abafa0bc0bc07 peer.Head=0x94d1e81990af84df92be844ad96110e9dbd096f64faa81c4cd5923c751c27f09 peer.height=521778
INFO[05-30|03:20:09.708] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="1.68 kB" elapsed=4.802ms hash=0x94d1e81990af84df92be844ad96110e9dbd096f64faa81c4cd5923c751c27f09 mgas=0 mgasps=0 number=521778 txCounterAfterStartup=1136 txs=0
INFO[05-30|03:20:19.716] Synchronization Started                       Line="syncer/syncer.go:430" local height=521778 peer=5960fac611f48724 peer.Head=0x7b693afadcfc1a7dd9f8f05b89b547f46d8d8094526523689e2c76dbaf9b9f3b peer.height=521779
INFO[05-30|03:20:19.721] Imported new chain segment                    Line="core/blockchain.go:1577" blocks=1 cache="1.71 kB" elapsed=3.688ms hash=0x7b693afadcfc1a7dd9f8f05b89b547f46d8d8094526523689e2c76dbaf9b9f3b mgas=0 mgasps=0 number=521779 txCounterAfterStartup=1136 txs=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbe6603]

goroutine 109 [running]:
bitbucket.org/cpchain/chain/core.(*txSortedMap).AllBefore(0xc0011f6b40, 0xbf33e9c8d2c2ec9d, 0x10283c10e800, 0x1d563e0, 0xbf33e9c8d2c2ec9d, 0x10283c10e800, 0x1d563e0)
	/ext-go/1/src/bitbucket.org/cpchain/chain/core/tx_list.go:250 +0xd3
bitbucket.org/cpchain/chain/core.(*txList).AllBefore(...)
	/ext-go/1/src/bitbucket.org/cpchain/chain/core/tx_list.go:418
bitbucket.org/cpchain/chain/core.(*TxPool).loop(0xc002805340)
	/ext-go/1/src/bitbucket.org/cpchain/chain/core/tx_pool.go:434 +0x743
created by bitbucket.org/cpchain/chain/core.NewTxPool
	/ext-go/1/src/bitbucket.org/cpchain/chain/core/tx_pool.go:341 +0x4cf

**To Reproduce**
Steps to reproduce the behavior, and the commands you use.

**Expected behavior**
RNode software should not crash

**Screenshots**
Not relevant, does not give any extra info

** Configuration (please complete the following information):**
 - OS: Centos 7
 - cpchain version 0.2.10

**Additional context**
Complete RNode logging:

[RNode log.txt](https://github.com/CPChain/chain/files/3235992/RNode.log.txt)

**Comment by alex031029** [comment]
It looks a severe problem. I have added an issue in our sprint broad as shown below. 
![image](https://user-images.githubusercontent.com/2452221/58743034-e9730e00-845c-11e9-9e33-1deef752af34.png)

And could you tell me how frequently you meet this panic error?

**Comment by HKet** [comment]
Hi Yanchen,

I have had this problem once, it occured after several days of running on 2.10. 

So it looks like a serious problem which can be hard to reproduce

Grt,
Hans Ketelaars

**Comment by alex031029** [comment]
Nailed it in 0.2.11. Close the issue :)
