### ISSUE TITLE
Request for possibility to see how RPT is build up for a node at current time via fusion or console

### ISSUE THREAD

**Issue by kbaf** [CPChain/chain#61]
Hello team,

With all the analytics i have done last few weeks, there is one thing which leaves me in the dark and that is how the RPT is build up for a node at a specific moment.

It's now easy to determine how a node is performing compared to other nodes, but the only visible aspect to make any conclusions about performance is the size of the balance.

Because other factors are also involved in creating a RPT value for a node it could be very helpfull if we could have insight in the status of those values at a specific time.

Thus, not only the result of the relevant variables, but also the numbers of that variables itself.

If we could have insight in RPT value via console or perhaps fusion, this would help us node runners very much to monitor the node's behaviour and notice and act on possible issues you may conclude of these variables.

It would also be in the interest of the network that we know more about this, if we can improve our node to be able to grow in reputation, the network will also be stronger and faster.

**Comment by alex031029** [comment]
It seems like you are wishing to have APIs for all factors that constitute RPT. 

At the current stage we do not have these APIs, and we do not store these information. Only In log these information are displayed.

**Comment by siebeneicher** [comment]
Still this is a request to provide such in formation via API. Are you not planning or wanting to add this information? Any security concerns?
