### ISSUE TITLE
Improve security for running an rnode

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#64]
In the public beta we had to sign our wallets for assigning a number of tokens to the smart contract. Will this method be used when RNodes go into production mainnet?

If not, I'd like to stress there should be no risk involved in running an rnode, keeping tokens exposed to hackers. 

I also expect CPChain to provide advice to keep the RNodes protected as much as possible. 

What ports must be exposed to the internet?
Can we use alternate ports?

A password for starting the chain should be a complex password, not like now it can be a single character password.

What else have you planned to increase security?

**Comment by alex031029** [comment]
Hi there, sorry for replying you late. 

For the port issue, you can use any port as you wish.
For the password issue, you can personally set a complex password. ETH and Linux password itself can be pretty simple, so we do not set a requirement for a password complexity.

**Comment by hvredevoort** [comment]
See my other issue related to security
