### ISSUE TITLE
My Node went several times in hibernation mode with v0.2.11

### ISSUE THREAD

**Issue by edat10000** [CPChain/chain#65]
Dear CPC team,

After upgrading to v0.2.11 I have had problems instantly and did not seal blocks. I restarted the node several times and also my server. When looking in the CMD prompt I noticed that my node stopped working for a long time and started again when i pressed the enter button.
After days of trying it sealed blocks but i had a high number of impeached blocks.

Best Regards
Onno

**Comment by alex031029** [comment]
Sorry that I reply you late. 
Despite that the beta testing has finished, the impeached blocks are still a problem perplexing us. 
As for the case of stopping node, I personally have never encountered similar situation, neither have I heard from other participants.
