### ISSUE TITLE
Enable Websocket for event subscription

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#66]
In order to avoid polling, I would like to use the Websocket API to subscribe to events, like:

```
const web3 = new Web3('ws://127.0.0.1:8546', null, {});
web3.eth.subscribe('logs', {}, (error, result) => {
	console.log('log:', result, error);
});

```

Please enable WS Api.

**Comment by alex031029** [comment]
Hi there,

Currently WS APIs are not available. We delete it from our forked web3 repo, to reduce our workload. I know that people are wishing various type of API, including WS and JS. I think we will gradually enrich our API tool.
