### ISSUE TITLE
Generation Block Info has inconsitent addresses (non-checksum and checksum)

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#68]
Dealing with the generation block info api, I see that some addresses are checksum and some non-checksum addresses. Here an example:

![image](https://user-images.githubusercontent.com/966545/59983610-c251cb80-9619-11e9-8f31-1779e5853b6f.png)

Please make sure, to allways deliver checksum addresses via the API.

**Comment by alex031029** [comment]
It does look weird! Although both version of address 0005ef contain upper letters (i.e., both version are checksum), they hold different sets of upper letters. 

I have reported this issue to the team. Thanks for you information.

**Comment by alex031029** [comment]
![image](https://user-images.githubusercontent.com/2452221/59989477-e50fce80-9671-11e9-81b6-a41f2ca533dd.png)
We tried fusion API, and the result showed non-checksum addresses. May I know how could I reproduce the result of original post?

**Comment by siebeneicher** [comment]
It seems it was a mishandling on my side, I used the web3.eth.toChecksumAdress and it was not performing properly. I appologize, this issue is NOT on cpc side.
