### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hvredevoort** [CPChain/chain#7]
Hi there, 
This is CPChain team. Note that this is for bug report. If you are requesting a feature, please select *Feature Request* template. 

**Where does the bug occur?**
[e.g. the chain, the wallet, the console or the explorer]

On Linux terminal starting cpchain after CTRL-C

**Describe the bug**

panic: runtime error: invalid memory address or nil pointer dereference
Many people reported this error on 0.2.3

INFO[05-08|10:01:20.812] Unlocked account                              Line="cpchain/cmd_account.go:205" address=0x1D93a6d7c9169b06F4C5Fb8f9307C69192865CE3
INFO[05-08|10:01:21.897] start participating campaign                  Line="cpc/backend.go:411" campaign=true
INFO[05-08|10:01:21.897] Transaction pool price threshold updated      Line="core/tx_pool.go:558" price=18000000000
INFO[05-08|10:01:21.897] Starting mining operation                     Line="miner/miner.go:105"
INFO[05-08|10:01:22.881] Mining aborted due to sync                    Line="miner/miner.go:76"
INFO[05-08|10:01:22.881] goroutine wait() quit                         Line="miner/engine.go:333"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xac5fb2]

goroutine 342 [running]:
math/big.(*Int).Uint64(...)
        /usr/local/go/src/math/big/int.go:382
bitbucket.org/cpchain/chain/consensus/dpor/rpt.(*RptCollectorImpl).RankInfoOf(0xc0000e49a0, 0x150d70a02f5932fe, 0x1b20121f535d32e8, 0xc0f554c121, 0xc001452dc0, 0xf, 0xf, 0x54f27, 0x4, 0x32)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/rpt/rpt.go:544 +0x102
bitbucket.org/cpchain/chain/consensus/dpor/rpt.(*RptCollectorImpl).RankValueOf(0xc0000e49a0, 0x150d70a02f5932fe, 0x1b20121f535d32e8, 0xf554c121, 0xc001452dc0, 0xf, 0xf, 0x54f27, 0x4, 0xfd983d8157ee3990)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/rpt/rpt.go:460 +0x84
bitbucket.org/cpchain/chain/consensus/dpor/rpt.(*RptCollectorImpl).RptOf(0xc0000e49a0, 0x150d70a02f5932fe, 0x1b20121f535d32e8, 0x5087f554c121, 0xc001452dc0, 0xf, 0xf, 0x54f27, 0x0, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/rpt/rpt.go:440 +0x136
bitbucket.org/cpchain/chain/consensus/dpor/rpt.(*RptServiceImpl).CalcRptInfo(0xc000468500, 0x150d70a02f5932fe, 0x1b20121f535d32e8, 0x3afa7724f554c121, 0xc001452dc0, 0xf, 0xf, 0x54f27, 0x0, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/rpt/rpt.go:211 +0xe6
bitbucket.org/cpchain/chain/consensus/dpor/rpt.(*RptServiceImpl).CalcRptInfoList(0xc000468500, 0xc001452dc0, 0xf, 0xf, 0x54f27, 0xc002172be0, 0x10, 0x10)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/rpt/rpt.go:196 +0x191
bitbucket.org/cpchain/chain/consensus/dpor.(*DporSnapshot).updateRpts(0xc001bcb180, 0x1290dc0, 0xc000468500, 0x0, 0x0, 0x0, 0xc, 0xc001c67e60)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/snapshot.go:404 +0x26c
bitbucket.org/cpchain/chain/consensus/dpor.(*DporSnapshot).applyHeader(0xc001bcb180, 0xc0013ef400, 0x1, 0x127b8a0, 0xc0004a1350, 0x1290dc0, 0xc000468500, 0xc00134d498, 0x43e921)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/snapshot.go:322 +0x63d
bitbucket.org/cpchain/chain/consensus/dpor.(*DporSnapshot).apply(0xc0019aa480, 0xc001b837c0, 0x1, 0x1, 0x1, 0x127b8a0, 0xc0004a1350, 0x1290dc0, 0xc000468500, 0xd9a3135897fe456d, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/snapshot.go:289 +0x257
bitbucket.org/cpchain/chain/consensus/dpor.(*defaultDporHelper).snapshot(0xc00031f290, 0xc0003bb1e0, 0x12a4520, 0xc00021a000, 0x54f27, 0x70083a151ab54fca, 0xead19070d89d775c, 0x25f57cb0fb3638b9, 0xe7f7c8f48f383a2c, 0xc0012b3580, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/dpor_helper.go:467 +0xb60
bitbucket.org/cpchain/chain/consensus/dpor.(*defaultDporHelper).verifySignatures(0xc00031f290, 0xc0003bb1e0, 0x12a4520, 0xc00021a000, 0xc0013ef680, 0xc0012b3580, 0x5, 0xf, 0xc000526f00, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/dpor_helper.go:575 +0x303
bitbucket.org/cpchain/chain/consensus/dpor.(*defaultDporHelper).verifyHeader(0xc00031f290, 0xc0003bb1e0, 0x12a4520, 0xc00021a000, 0xc0013ef680, 0xc0012b3580, 0x5, 0xf, 0xc000526f00, 0xc0004d0001, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/dpor_helper.go:121 +0x282
bitbucket.org/cpchain/chain/consensus/dpor.(*Dpor).VerifyHeaders.func1(0xc0012b3580, 0xf, 0xf, 0xc0003bb1e0, 0x12a4520, 0xc00021a000, 0xc0012b3600, 0xf, 0xf, 0xc0004d3700, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/consensus.go:122 +0x191
created by bitbucket.org/cpchain/chain/consensus/dpor.(*Dpor).VerifyHeaders
        /ext-go/1/src/bitbucket.org/cpchain/chain/consensus/dpor/consensus.go:120 +0x145
hv@hvmgmt01:~/cpchain$

**To Reproduce**
Steps to reproduce the behavior, and the commands you use.

./cpchain run --datadir ./dd --unlock 1d93a6d7c9169b06f4c5fb8f9307c69192865ce3 --rpcaddr 127.0.0.1:8501 --port 30311 --mine --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber

**Expected behavior**

**Screenshots**

** Configuration (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - cpchain version [e.g. 0.2.3]
Ubuntu 18.04
cpchain 0.2.3
16GB memory, 8 core, 1250GB SSD

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
Several people have encountered same panic problem as yours. This bug has been fixed but yet merged into the master nor published. The next version will get this problem fixed.
