### ISSUE TITLE
rnode api not returning data since 0.4.5

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#70]
My civilian node started via: `cpchain-0.4.5 run --datadir ./datadir --rpcaddr 127.0.0.1:8501 --port 30311 --rpcapi personal,eth,cpc,admission,net,web3,db,txpool --linenumber`

Using the python RPC api to request rnode:

`
from cpc_fusion import Web3
from cpc_fusion.middleware import geth_poa_middleware
cf = Web3(Web3.HTTPProvider('http://127.0.0.1:8501'))
cf.cpc.getRNodes     // returns: null
`

the return during testnet was a list with rnodes. is this a bug or feature to limit access to the rnode information?

**Comment by alex031029** [comment]
Okay, it is a trick of invoking rnode API. 

As you state, you are running a civilian node without a flag `--mine`. RNode information is only meaningful for node that are willing to mine (i.e., the node with `--mine`). Thus, rnode API is only available if you are running a node with `--mine` flag. 

In case that you still want to retrieve rnode information as a civilian, you can run a node with `--mine` and insufficient balance. It is also how our explorer retrieves rnode information from a civilian node.
