### ISSUE TITLE
BlockChain Explorer / Blockchain binary code verification vs source code verification

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#74]
Hi CPC_Team,

**Is your feature request related to the chain, the wallet, the console, the explorer, or other aspect?**
Explorer

**Is your feature request related to a problem? Please describe.**
Yes, now we have trust the CPChain when you write a Smart Contract (SC) that this smart contract do what you say. If a private person want to write a Smart Contract how other people can trust my or the contract of this person? E.g. i wanted to check after how many days i will get back my  CPCs from my RNode when i will stop. I was checking the SC address and i found just hexnumber.

https://cpchain.io/explorer/address/0x76130da5aa1851313a7555d3735bed76029560da

There is no  manual how to decode it... and better it would be if you can realize it like it is done on EtherScan.io:

https://etherscan.io/address/0xf412af62269a0b3b10ea727df81231cdc5bb6364#code

here i can read the contract and  i dont have to trust the person who wrote the contract... if i have to trust the person why should the person write a SC and not a normal application?

**Comment by yuppieghost** [comment]
Hello, Mateus224, I'm the developer in charge of CPChain Explorer.
Thanks for your suggestion, but there's no way to decode a contract from the bytecode to ABI or source code actually. 
As for etherscan.io, their abi/sourcecode is uploaded from who deployed the contract. With validation from the server of etherscan, you can now see **some** of the SC source code and abi.
You can see the source code of RNode Contract in [the CPChain repo](https://github.com/CPChain/chain/blob/HEAD/contracts/dpor/rnode/rnode.sol), there is source code of our contract.
We will consider adding this feature in the future.

**Comment by Mateus224** [comment]
okay just a suggestion: How about that after the source code binary has been converted you would also add a hash of the source code on the end. Thus, anyone who read a source code published somewhere could even calculate the hash and check it on the blockchain SC address the same hash on the end of the binary file is added and see if the SC address does what is promised.
