### ISSUE TITLE
RNode software unexpectedly killed

### ISSUE THREAD

**Issue by HKet** [CPChain/chain#77]
**Where does the bug occur?**
chain

**What is your wallet address and your balance?**
aks Yanchen he is informed about this issue 

**Describe the bug**
All of a sudden after several hours of mining (about 16) the RNode software was killed without showing a stack trace or something like that.

The question from Yanchen in TG about empeached blocks learned us that around the same time 00:58 4 impeached blocks occured.

Investing the processes learned that it is probably caused by an Out Of Memory problem.
The following :
![telegram-cloud-photo-size-4-5933973197961670924-y](https://user-images.githubusercontent.com/24922860/62726772-46201580-ba18-11e9-8e55-9ff13b367cff.jpg)
was the result of dmesg | grep cpchain 

Additional info: the impeached block where not visible in the RNodes.io tool. After an update by Marcus they are, maybe Marcus can explain why they weren't visible at first and can help this additional info.

**To Reproduce**
??? 
I do not know how to force impeached block and let it result in an Killled state

**Expected behavior**
RNode software is robust against OOM and has correct recovery behaviour

**Screenshots**
screenshot at time of crash:
![image](https://user-images.githubusercontent.com/24922860/62727100-01e14500-ba19-11e9-956c-c3a1131e67f3.png)
The Killed message was the last message in the terminal, no stack dump or additional information
screenshot of system usage a few hours before crash:
![image](https://user-images.githubusercontent.com/24922860/62727325-8c29a900-ba19-11e9-9580-2cc2468500b5.png)

** Configuration (please complete the following information):**
 - Centos 7
 - cpchain Rnode V0.4.6

**Additional context**
I have had contact with Yanchen via PM in Telegram. He has additional info

**Comment by alex031029** [comment]
Some info updates. Hket informed that a same OOM problem happens again around two hours ago. 
Here I attach the figures of the message and `top` command outputs

![image](https://user-images.githubusercontent.com/2452221/62757403-cf355c00-baad-11e9-8975-a974b18668cd.png)

![image](https://user-images.githubusercontent.com/2452221/62757420-d8262d80-baad-11e9-9bdf-4bf9e99d717c.png)

**Comment by alex031029** [comment]
In a nutshell, this problem is caused due to OUT OF MEMORY(OOM). And the `cpchain` binary file is killed by OS. 

As HKet informed me in telegram, his sever has a specs of 4GB which suffices to running a proposer node. And another large process running with `cpchain` is remote desk. 

As this problem happens twice on his machine, there must be some reasons behind it. My current speculations are that the following may account for the problem:
1. The remote desk consumes more memory than we expected
2. The some other system process drain all computing power. As shown in the figure in previous post, a system process `tracker-store` occupied 98.7% of CPU resource.
3. The peak space consumption of `cpchain` outnumbers 4GB. Despite that it is the first case that reports OOM problem for the latest version, usually users can easily dismiss a simple `killed` or `out of memory` error message. Thus, I truly appreciate HKet's scrutiny on this error.

**Comment by HKet** [comment]
i have been observing my RNode system for some minutes just now and saw that at particular moments 3 Tracker-store processes popped up in the top view. 

![Schermafbeelding 2019-08-11 om 07 18 19](https://user-images.githubusercontent.com/24922860/62830301-1be37900-bc0d-11e9-90a2-e866b02a5c21.png)

A grep on Tracker-store following on ps-ef command resulted in the following:

![Schermafbeelding 2019-08-11 om 07 41 45](https://user-images.githubusercontent.com/24922860/62830330-62d16e80-bc0d-11e9-87e1-6bd563ae4af9.png)

As you can see these processes are all running quite some time now.

Is this normal?
Is it due to the fact that i had 2 RNode crashes (Killed) and i just restarted the RNode software again without rebooting the system after a crash, in other words are these ghost processes?

If this is the case than at least i find it strange that now and then they popup in the top 3 processes showed by the "top" command and use about 15% cpu. As you can see the first proces almost consumes 90%

**Comment by alex031029** [comment]
After I searched `tracker-store`, I found that there are a large amount of complaints about this process consuming too many CPU and disk resources. Some people suggests to disable `trakcer-store`. 

And one of our own civilian node which has 2GB memory reports a similar OOM error. It can help us investigate the situation. And I will update this issue if I find any new discoveries.

**Comment by HKet** [comment]
This morning i had another crash of this kind.
Watching the system resulted in the following:
![telegram-cloud-photo-size-4-5949684897000042321-y](https://user-images.githubusercontent.com/24922860/62965521-8c54ea80-be05-11e9-88e4-92130a2643ba.jpg)

Just a few minutes ago i searched the internet for a possible solution and found out that this tool is not limited to Centos but is used on several other Linux like products for instance Ubuntu.

This is inline with the remark you made in TG and so the problem can indeed occur on other unix related Nodes as well.

As stated in a PM to you in TG i am willing to remove the Tracker/Search software from the RNode and see what happens. But before i will do that can you tell me whether the RNode software is depending on this feature?

I found this page on internet https://www.linuxuprising.com/2019/07/how-to-completely-disable-tracker.html and want to do this and see what happens

**Comment by HKet** [comment]
This morning i had another Killed state resulting in 9 empeached blocks
![Schermafbeelding 2019-08-14 om 22 03 48](https://user-images.githubusercontent.com/24922860/63052433-99dea300-bedf-11e9-9d8f-cc46efd6d0ff.png)

The solution as proposed on the page from the URL above did not work.
However i succeeded in killing the tracker processes for now and let it run to see whether the issue  is gone.
I will keep you informed

Keep in mind that this is not a structural solution, this should come from CPC by solving this OOM issue in the software

**Comment by alex031029** [comment]
I have add warning on https://docs.cpchain.io/preliminaries/overview.html#hardware-specification of this issue. Users should be cautious of memory and CPU consumption of their servers. 

![image](https://user-images.githubusercontent.com/2452221/64156847-1d007280-ce68-11e9-8945-9e3d58436d2c.png)
