### ISSUE TITLE
API for detailed RPT 

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#79]
Hi there,

**Is your feature request related to the chain, the wallet, the console, the explorer, or other aspect?**
chain and explorer

**Is your feature request related to a problem? Please describe.**

It would be good to see for the community what in detail the RPT is, not only the result of all 5 weights, but to see every single weight of the RPT (transaction, CPC amount...) it would answer many questions of the community and maybe there would be less questions.

**Comment by hvredevoort** [comment]
I’d certainly be in favor of showing more detail of RPT and it would stimulate rnode holders to optimize balance, size, location, speed, capacity etc of their rnode
