### ISSUE TITLE
Script for email receiving when RNode was killed

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#81]
Hi 
I wrote today a short script which checks if my Rnode lives or was killed (OOM or somthing else what could happen in the long term). This script sends after the Node was killed to myself  an email (So I dont have check every day if the server is running).  I want add in the next days the output of the last error from my Node too, before the RNODE has died.   

Now i started to think that it could be for the CPC team interesting too, to get all this informations relatime, so that you would get the errors automatically with an email with all the informations when a node was killed. Maybe i could even add Hardware informations about the server etc. to the email. So that Alex then dont have ask always about this informations in the Telegram group.

I just was writing a hour this script its not perfect but it do what it has to do. And it should work on Windows and Linux (just tested on Linux).

https://github.com/Mateus224/CPC_RNode_liveCheck

**Comment by alex031029** [comment]
I do think it is a good feature. Do you suggest us to add a similar notification feather on the chain?

**Comment by hvredevoort** [comment]
https://github.com/Mateus224/CPC_RNode_liveCheck/issues/1
