### ISSUE TITLE
With the current Wallet version its not possible to call a fallback function in a SC

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#82]
Hi there,

**Is your feature request related to the chain, the wallet, the console, the explorer, or other aspect?**
 
Wallet

**Is your feature request related to a problem? Please describe.**

I m writing a SC for the community. The SC has a fallback function to make it easier for everyone to execute the SC. But the fallback function needs more Gas as an normal transaction. So i checked your Wallet video on youtube if there is is a possibility to adjustable how much Gas will be sent. But to my regret I see that the App only displayed how much gas is consumed and that is not adjustable. I hope that this can be improved, because I probably will not be the only one who writes an SC who wants to use a fallback function in his SC.

https://www.youtube.com/watch?v=Ol5rwIrp3CA

**Describe the solution you'd like**
Make the Gas adjustable by sending CPCs. And just write a suggestion how much Gas is  needed for a normal transaction.

**Comment by alex031029** [comment]
I have asked my teammate in charge of wallet, he said at the current stage, the gas limit cannot be adjusted. Usually, wallet is used for normal transaction, not for smart contract. Therefore, we don't design a mechanism in wallet to adjust the gas.

But in SC, you can set whatever the gas you want. I didn't really get your point, in what situation you require an adjustable gas in wallet？

**Comment by Mateus224** [comment]
I m designing a game with some game theory so that people can bet which number somebody else is betting (its for the community). To make it for everybody as easy as possible i wanted that people can through a normal transaction take part on this game. So they dont need a special program to call the functions in the contract address. If somebody will send a transaction to my contract address the fallback function will be called.  But to make the calculations in the Fallback function is more Gas needed then in a normal transaction. So the problem is not to set the gas in SC, but to make it easy for everybody to take part on the game without special programs which will execute the SC functions just through sending CPC on this address, which would call the fallback functions in the SC (The argument of the betting number would be the last number of CPC (in Wei) e.g. 1.000...00000018). So EVERYBODY could take part on this game... but now i see i have to implement something like game wallet which will send enough Gas to call the fallback function. Do you understand what i mean? 

https://github.com/Mateus224/CPC_SC_game_theory_game/blob/master/gameTheoryGame.sol
