### ISSUE TITLE
Rnode does not seal blocks

### ISSUE THREAD

**Issue by martijnvdweerdt** [CPChain/chain#83]
Hi there, 
This is CPChain team. Note that this is for bug report. If you are requesting a feature, please select *Feature Request* template. 

**Where does the bug occur?**
In the chain. 

**What is your wallet address and your balance?**
0x6D353d1943D0Da970fd7DBD3fdAB64D3C21C6877

**Describe the bug**
I have set up a new Rnode (Windows Vultr VPS). The chain has synced, a new part of the chain is added every ten seconds, but the node itself is not sealing any blocks. It might have something to do with a previous node I had that I killed, but I am not sure. 

**To Reproduce**
Downloaded the newest CPC release and made Keystore file. The Keystore file and CPC code were transferred to the VPS and this command was run in the VPD cmd prompt: cd cpchain , 

cpchain.exe run --datadir ./datadir --unlock 0x6D353d1943D0Da970fd7DBD3fdAB64D3C21C6877 -- rpcaddr 127.0.0.1:8501 --port 30311 --mine —rpcapi  personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber

This works, the chain syncs and everything looks good. But not sealed blocks even not after many hours. 

**Expected behavior**
Maybe I cannot reach the port 30311. If this is the case, it is not due to a firewall in the VPS, this was already checked. Also, I noticed that after shutting down the previous node, the 200k CPC tokens were not returned, maybe this is also the new node using the same adress cannot seal blocks. 

**Screenshots**

** Configuration (please complete the following information):**
 - OS: Windows VPS
 - cpchain version 4.7

**Additional context**
There might be a correlation with the previous node I had but that I killed (stopped running the code). It was a Linux Vultr VPS which I assesed through a VM Ubuntu on a Windows laptop. This node was running and also sealing blocks but the connection did not remain alive (even after tmux).

**Comment by alex031029** [comment]
Martijn had informed me of this issue a few days ago in telegram. 
Referred from the explorer: https://cpchain.io/explorer/address/0x6d353d1943d0da970fd7dbd3fdab64d3c21c6877, we can see that the node has not sealed any block for 12 days. And only one transaction was sent from the node, which was 2 days ago. 

Thus, the node have not been claiming for campaign in recent 12 days.

Meanwhile, Martijn told me that his node had been suffering from an SSH problem. Trippledutch from telegram group helped him to launch the node on Windows. My speculation was that Martijn's broken SSH incurred his failure in claiming campaign. However, his node on Windows cannot solve the problem.

Now I need more info, especially screenshots of his node, to investigate the situation.

**Comment by martijnvdweerdt** [comment]
The transactions till 12 days ago were on my linux node which I assessed through the vm on my computer, unfortunately the ssh could not remain alive (but it could claim campaign). 

Not claiming campaign started since I switched to a Linux node (using same CPC adress). This node send only one transaction and could not seal any block. It was checked and one of the problems is that the proper port is not open for this specific node. I have attached several printscreens (there are not really error alerts in the command prompt). 

Failed port connection:
![Screenshot 2019-08-30 at 15 12 40](https://user-images.githubusercontent.com/54245216/64149590-8bbcdc00-ce26-11e9-9f23-164c91795055.png)

This is not due to firewall rules:
![Screenshot 2019-08-30 at 15 14 00](https://user-images.githubusercontent.com/54245216/64149591-8c557280-ce26-11e9-89ad-7963709600c9.png)

This is one of the messages when starting up Vultr VPS(1/2):
![Screenshot 2019-08-30 at 14 48 57](https://user-images.githubusercontent.com/54245216/64149654-c1fa5b80-ce26-11e9-9910-e98e5de499f1.png)

This is one of the messages when starting up Vultr VPS(2/2):
![Screenshot 2019-08-30 at 14 58 27](https://user-images.githubusercontent.com/54245216/64149655-c1fa5b80-ce26-11e9-89dc-a791928ca18d.png)

Printscreens from starting up the node and lines of code when node is running (1/2):
![Screenshot 2019-08-30 at 13 24 41](https://user-images.githubusercontent.com/54245216/64149732-0554ca00-ce27-11e9-8b40-79a57bcb4632.png)

Printscreens from starting up the node and lines of code when node is running (2/2):
![Screenshot 2019-08-30 at 13 38 51](https://user-images.githubusercontent.com/54245216/64149772-1f8ea800-ce27-11e9-918e-2dba9bfde8fc.png)

**Comment by alex031029** [comment]
To be honest, the screenshot you provided look fine for me. It does not has error message. Therefore, I am quite confused by your case. I have informed my teammates of this issue, and we are try our best to find a solution for me.

**Comment by alex031029** [comment]
I just witnessed transactions from the node!

![image](https://user-images.githubusercontent.com/2452221/64155883-45876d00-ce66-11e9-94ee-fc95053c131b.png)

Martijn told me that he has restarted already ten times before but it didn't work. The difference now is that he pasted the code in the vps code prompt itself instead of log in with teamviewer on the vps and then paste in the vps code prompt

He is pretty sure that when before I log in with vps everything works including syncing but claiming campaign does not start. Only when pasting code directly in vps from the internet browser, campaign claims.

**Comment by hvredevoort** [comment]
This can be closed because the node has been running for some time
