### ISSUE TITLE
Failed to check network status, try to dial

### ISSUE THREAD

**Issue by CalRon07** [CPChain/chain#84]
Hi there, 

**Where does the bug occur?**
The Chain

**What is your wallet address and your balance?**
0x9c774c69007f52705acce77a64c405299b1fb1fa

**Describe the bug**
I needed to perform a fresh install with the latest update, which included downloading chaindata.  Once the node synced with mainnet, I received the following warning whenever there was a Campaign for Proposer Committee: "fail to check network status, try to dial."

When I did a fresh install with 0.4.7, I noticed the chaindata folder only contained 8 GB of data, whereas with 0.4.5 and 0.4.6 the folder had 23GB data.  

I decided to downgrade and do a fresh install with 0.4.6 (all 23 GB of data downloaded in chaindata folder), but I still received the same warning.

I downgraded again to 0.4.5 and still receive the same warning. 

For some reason my node will download the chain data and sync with mainnet, but I keep getting a network status failure.

**To Reproduce**
Fresh install 0.4.5, 0.4.6, and 0.4.7 all produce the same warning.  Node will not produce blocks.

**Expected behavior**
Download chaindata, sync with mainnet, and produce blocks like my node used to do without issue.

**Screenshots**
![Uploading Screenshot from 2019-09-02 02-47-03.png…]()

** Configuration (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - cpchain version 0.4.5, 0.4.6, and 0.4.7 (currently on 0.4.7)

**Additional context**
Have not produced blocks for over 24 hours now.  I ran a node during beta test, and ran a node on mainnet since August 1st without issues.  Everything I have done is the same, but this time it will not connect.  I am out of ideas as to how to correct the problem.

**Comment by alex031029** [comment]
"fail to check network status, try to dial." is a error message when your network is not fast enough.

In AC (admission control), we evaluate your network condition via pinging a Microsoft website. If the delay is larger than 300ms, we consider your network is not suitable for sealing blocks, and you will get this error message.

**Comment by CalRon07** [comment]
I wont be home until the 6th, but I never had a problem before and I have a 1 Gbps up and download bandwidth.  I run a masternode with High Performance Blockchain as well with a different server and same bandwidth with no issue, and their requirements are greater than CPChain.

I have pinged my server with them in the past and it is as litle as 2-3ms.  Ive never had a speed greater than 300ms.

I believe the issue is something else.  Why would my node work perfectly fine on mainnet for 30 days?  I didnt have the issue until I accidenatlly erased the chaindata folder.  I then needed to do a fresh install, and that is when the issue happened.

**Comment by CalRon07** [comment]
Update:

Checked my balance and noticed I have proposed 9 blocks since my last post.  Do not have a way of diving deeper into this because I am out of town, but at least the node is/was running at some point.  I'll come back on the 6th if I am still having issues.

Thank you

**Comment by alex031029** [comment]
Glad to hear that your node has sealed some blocks. 

The network you hold is far above our requirement. Thus, it shouldn't be the bottleneck.

As you cleared the `chaindata` folder, you had to sync the chain from the very beginning again. It should not affect your sealing after fully synced. 

Well, since you can seal blocks again, I hope it does not reflect an error of the chain. I will keep this issue open for several days. If you encounter the same problem again, please post here. And I will close it if nothing updated then.

**Comment by CalRon07** [comment]
Final Update:

Node has not encountered any issues since it started to work again.  I am sealing the same average of blocks per day.

Not sure what the issue was, but I believe I had the same warning the very first time I launched my node when mainnet was released.  The first time it auto corrected after 40 minutes.  This time it took over 24 hours.

Either way, Im back in business.  Thank you!
