### ISSUE TITLE
The folder `chaindata` occupies unexpectedly large space.

### ISSUE THREAD

**Issue by alex031029** [CPChain/chain#87]
**Where does the bug occur?**
the chain

**Describe the bug**
The bug is firstly reported by TokenInsight, an industry node. The `~/.cpchain/cpchain/chaindata` (default directory storing chain files) of TokenInsight is around 48 GB, which contains more than 40k ldb files. 

In comparison, out team node only occupies around 15 GB with 15k ldb files stored.

![image](https://user-images.githubusercontent.com/2452221/64664993-8ba28900-d483-11e9-8cfe-4cb1bacfa9d1.png)
![image](https://user-images.githubusercontent.com/2452221/64665000-92310080-d483-11e9-851b-29bf43332208.png)
![image](https://user-images.githubusercontent.com/2452221/64665006-9826e180-d483-11e9-9e2d-a7f9ce0a90d7.png)
![image](https://user-images.githubusercontent.com/2452221/64665134-01a6f000-d484-11e9-8168-f40cf281eaf4.png)

**Comment by alex031029** [comment]
The users from telegram also reported to me about their disk consumption. I conclude here:

43, 24, 41, 43, 18, 45, 40.9 (GB)

**Comment by hadox** [comment]
Just did a clean install of my rnode and now my chaindata is 7.85GB. 
Huge difference :)

**Comment by alex031029** [comment]
A good news is that we have find a way to remove temporary and redundant files. A new command  which can reduce the disk consumption to 10% of the original one, will be embedded in the new version. Now the new version is under testing :)

**Comment by hadox** [comment]
Good to hear Alex. Thanks!

**Comment by alex031029** [comment]
This problem has been fixed in 0.4.8, in which two commands are implemented to reduce the oversized disk occupation.
