### ISSUE TITLE
RNodes amount changes drasticially per term

### ISSUE THREAD

**Issue by siebeneicher** [CPChain/chain#9]
Captured 2 rnodes terms from https://cpchain.io/explorer/rnode/:

Term 9669 had 14 RNodes
Term 9670 has 27 RNodes

Its big difference each term.

My RNode has high specs: Dual Xeon, 32GB RAM, fiber. Sometimes its included in the RNodes list, sometimes not at all, while we have only 14 RNodes. I assume with the amount of connected nodes we should have a relative stable amount of Rnodes each term.

![screencapture-cpchain-io-explorer-rnode-2019-05-08-10_27_57](https://user-images.githubusercontent.com/966545/57361364-8acbb480-717c-11e9-937e-1585403608c0.png)
![screencapture-cpchain-io-explorer-rnode-2019-05-08-10_29_54](https://user-images.githubusercontent.com/966545/57361365-8b644b00-717c-11e9-9457-4838b61cef4b.png)

**Comment by siebeneicher** [comment]
Again Term 9671 has only 14 RNodes, which seems totally unlogic.

**Comment by alex031029** [comment]
well, "RNode" here in the explorer is bit misleading. The number you see is actually referring to RNodes who has passed AC (admission control), which makes you notice the fluctuation of this value.

**Comment by alex031029** [comment]
This problem is supposed to be fixed in a future release.

**Comment by alex031029** [comment]
Nailed it! Close it.
