### ISSUE TITLE
Rnode sync error

### ISSUE THREAD

**Issue by xarlibcn** [CPChain/chain#91]
Hi,
After some days of running the node I started to get the following error and stopped to propose blocks:
"err when handling sync msg" "shutting down"

Restarting the node didn't have any effect. I clean DB and started to sync again, it propose several blocks but short after I'm seeing the same error again plus another one:
"write of tcp myip:30310 -> notherip:port use of closed connection"

My HD is only 40 Gb but it is only at 34% of use.

![image](https://user-images.githubusercontent.com/56462068/66693696-57b6bf80-ecde-11e9-8036-b0e991a8d877.png)

![image](https://user-images.githubusercontent.com/56462068/66693704-892f8b00-ecde-11e9-9d16-984c775864d4.png)

Any idea?

**Comment by alex031029** [comment]
It is a warning message, not an error. This warning message indicates that a peer in your peer list has disconnected from you. It is a message can be easily seen, since it is pretty normal that someone restarts its node. 

You can simply omit it. :)
