### ISSUE TITLE
cpchain process panic

### ISSUE THREAD

**Issue by scasli** [CPChain/chain#94]
The process restarted OK.

Here is the console log:

cer/syncer.go:431" local height=1147466 peer=b409c4db2c8a8432 peer.Head=0xe2a82f6c65aab5f1f6aa1f390e8cb69e276b88ab7940f19e688236a6c5dec14b peer.height=1147467
INFO[11-07|10:10:10.240] Imported new chain segment                    Line="core/blockchain.go:1592" blocks=1 cache="0.00 B" elapsed=1.943s hash=0xe2a82f6c65aab5f1f6aa1f390e8cb69e276b88ab7940f19e688236a6c5dec14b mgas=4.223994 mgasps=2.173833777821387 number=1147467 txCounterAfterStartup=120411 txs=31
INFO[11-07|10:10:17.311] Imported new chain segment                    Line="core/blockchain.go:1592" blocks=1 cache="0.00 B" elapsed=5.974ms hash=0x2ae6e1cfa5832f2f52c16d8a246beee19d04a786e9d7c65327a9270df11e6851 mgas=0 mgasps=0 number=1147468 txCounterAfterStartup=120411 txs=0
INFO[11-07|10:10:27.328] Imported new chain segment                    Line="core/blockchain.go:1592" blocks=1 cache="0.00 B" elapsed=10.354ms hash=0xe5609628550083bdfcbb3493bbe82ebef68b5b3bf97170f71bbbf833d9ab7f97 mgas=0 mgasps=0 number=1147469 txCounterAfterStartup=120411 txs=0
INFO[11-07|10:10:37.292] Imported new chain segment                    Line="core/blockchain.go:1592" blocks=1 cache="0.00 B" elapsed=12.200ms hash=0x4ce8fd4cdae66b85e93fd73a2b07ca49e05346cfd6cdc4ae4de2773b5b35327d mgas=0 mgasps=0 number=1147470 txCounterAfterStartup=120411 txs=0
panic: sha3: write to sponge after read

goroutine 151 [running]:
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/crypto/sha3.(*state).Write(0xc002d7cc40, 0xc003e0e020, 0x8e, 0x4e0, 0xffffffffffffffff, 0xc00e613c74, 0xc00e613c80)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/crypto/sha3/sha3.go:127 +0x384
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/crypto.Keccak256(0xc00e613d48, 0x1, 0x1, 0xc00e613c80, 0xc00e613c74, 0xae)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/crypto/crypto.go:48 +0xb3
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover.decodePacket(0xc003e0e000, 0xae, 0x500, 0x7f157f9276d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover/udp.go:582 +0xe2
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover.(*udp).handlePacket(0xc0053f2b60, 0xc0051b6210, 0xc003e0e000, 0xae, 0x500, 0xc0051b6200, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover/udp.go:567 +0x5d
bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover.(*udp).readLoop(0xc0053f2b60, 0x0)
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover/udp.go:557 +0x249
created by bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover.newUDP
        /ext-go/1/src/bitbucket.org/cpchain/chain/vendor/github.com/ethereum/go-ethereum/p2p/discover/udp.go:271 +0x33b
cpcadmin@vmi301905:~$

**Comment by alex031029** [comment]
This error message is from "golang.org/x/crypto/sha3.go". So my current speculation is that it is caused by code dependency. In other word, some libraries imported may have update and it further causes some problems in CPChain. 

This kind of problems can be eliminated by regression testing. But it may take a long time to locate the bug, and the existing test cases may not cover it.

**Comment by scasli** [comment]
I have several Rnodes at the same VPS provider and each is configured identically. This problem happened on only one of them. There is a crontab job checking that cpchain is running, and as it's the first occurrence I'm happy just to restart the process if it happens again.
I'm curious to know if anyone else has experienced a similar issue.

**Comment by alex031029** [comment]
As far as I know, your node is also the only one that met this panic message. Apparently, it can hardly be reproduced, and currently we do not have a clear idea about the reason.
