### ISSUE TITLE
Ubuntu Error with fresh install on 0.5.1

### ISSUE THREAD

**Issue by nuht** [CPChain/chain#96]
Hi there, 

**Where does the bug occur?**
[e.g. the chain, the wallet, the explorer]
When syncing and trying to mine.

**What is your wallet address and your balance?**
If it is too private to answer, you can skip it. 

**Describe the bug**
If you are setting smart contract or sending transactions, make sure explicit all details including gas price. 

I tried to do a fresh install of my node using ubuntu.
Tried to sync the chain on 0.5.1 with that command.

'''./cpchain run --datadir ./datadir \
    --unlock address \
    --rpcaddr 127.0.0.1:8501 --port 30311 --mine \
    --rpcapi personal,eth,cpc,admission,net,web3,db,txpool,miner --linenumber'''

**To Reproduce**
Steps to reproduce the behavior, and the commands you use.
Fresh install on ubuntu, then sync the chain.

**Expected behavior**

**Screenshots**
The error is : FATA[11-20|22:52:17.785] failed to retrieve header from local chain    Line="rpt/rpt_helper.go:259" err="<nil>" after syncing.

I have the 200k deducted in my balance and I can't stop the campaign also. It says i'm not rnode already.

** Configuration (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] Ubuntu 18.04
 - cpchain version [e.g. 0.2.3] 0.5.1

**Additional context**
If your bug can only be reproduced occasionally, please emphasize it.

**Comment by alex031029** [comment]
Hi, there. 

I just received an error report similar to you, as shown below.
![Uploading image.png…]()

Now we are investigating the situation, and will keep you updated.

**Comment by nuht** [comment]
It's exactly what is happening to me

**Comment by alex031029** [comment]
Okay, we have figured out the reason. In short, it is due to the sync process.

When `cpchain` is syncing, it imported blocks in batch via multi threads. Thus, the blocks are not guaranteed to be imported in order. However, the new feature of 0.5.1, calculating impeached block number, requires an ordered blocks. 

We are going to publish a new version soon to fix the bug. Thanks again for you feedback.

**Comment by nuht** [comment]
Hi, 
I could solve the problem for myself with the 0.4.7 cpchain file.
I synced again,  then I could stop the campaign to get back the 200k cpc on my balance then I could switch the cpchain file to 0.5.1 and launch the run command and mine again.

Sorry if it's not totally clear.

**Comment by alex031029** [comment]
Awesome. Your operations worked since the sync process was redone. It can be used as an expedient. Anyway, a small update would be released soon.
