### ISSUE TITLE
27 impeached blocks in 24h

### ISSUE THREAD

**Issue by Mateus224** [CPChain/chain#99]
Hi there, 

**Where does the bug occur?**
chain

**Describe the bug**
how this adress can have 27 impeached blocks in 24h? I thought this is not possible with the new punishment algorithm 
- 0x84C7aec2E9503D033E7b5589a00eEf636Ab720E5

**Comment by CPC-Yao** [comment]
According to the current algorithm, there is indeed a small possibility that a node can produce some impeached blocks.
After a node generates impeached blocks, the system will gradually reduce its RPT to a minimum of 1000. As the total number of rnodes is currently small, it may still be selected.
We are considering a more severe punishment scheme.
